/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version fusioncharts/3.3.1-sr1.19666
*/
FusionCharts(["private","modules.renderer.js-charts",function(){function Ca(a){for(var J={left:a.offsetLeft,top:a.offsetTop},a=a.offsetParent;a;)J.left+=a.offsetLeft,J.top+=a.offsetTop,a!==E.body&&a!==E.documentElement&&(J.left-=a.scrollLeft,J.top-=a.scrollTop),a=a.offsetParent;return J}function W(a,J){for(var e=[],h=0,T=a.length;h<T;h++)e[h]=J.call(a[h],a[h],h,a);return e}function sa(a){a=(a||0)%ia;return a<0?ia+a:a}function Da(a,J){return a<=A?a:J<=A?J:J>a?0:J}function La(a,J,e,h,T){return I((J-
e[1]-h.top)/T,a-e[0]-h.left)}function Ea(a,J,e,h,T,b,k,t,c,o){if(typeof a==="object")J=a.y,e=a.r,h=a.innerR,T=a.radiusYFactor,b=a.depth,k=a.seriesGroup,t=a.renderer,a=a.x;if(T<0||T>=1)T=0.6;a=a||0;J=J||0;e=e||1;h=h||0;b=b||0;this.renderer=t;this.hasOnePoint=c;this.use3DLighting=o;this.cx=a;this.cy=J;this.rx=e;this.ry=e*T;this.radiusYFactor=T;this.isDoughnut=h>0;this.innerRx=h;this.innerRy=h*T;this.depth=b;this.leftX=a-e;this.rightX=a+e;this.leftInnerX=a-h;this.rightInnerX=a+h;this.depthY=J+b;this.topY=
J-this.ry;this.bottomY=this.depthY+this.ry;this.bottomBorderGroup=t.group("bottom-border",k).attr({transform:"t0,"+b});this.outerBackGroup=t.group("outer-back-Side",k);this.slicingWallsBackGroup=t.group("slicingWalls-back-Side",k);this.innerBackGroup=t.group("inner-back-Side",k);this.innerFrontGroup=t.group("inner-front-Side",k);this.slicingWallsFrontGroup=t.group("slicingWalls-front-Side",k);this.topGroup=t.group("top-Side",k);this.moveCmdArr=[d];this.lineCmdArr=[g];this.closeCmdArr=[m];this.centerPoint=
[a,J];this.leftPoint=[this.leftX,J];this.topPoint=[a,this.topY];this.rightPoint=[this.rightX,J];this.bottomPoint=[a,J+this.ry];this.leftDepthPoint=[this.leftX,this.depthY];this.rightDepthPoint=[this.rightX,this.depthY];this.leftInnerPoint=[this.leftInnerX,J];this.rightInnerPoint=[this.rightInnerX,J];this.leftInnerDepthPoint=[this.leftInnerX,this.depthY];this.rightInnerDepthPoint=[this.rightInnerX,this.depthY];this.pointElemStore=[];this.slicingWallsArr=[];a=[f,this.rx,this.ry,0,0,1,this.rightX,J];
e=[f,this.rx,this.ry,0,0,1,this.leftX,J];h=[f,this.rx,this.ry,0,0,0,this.rightX,this.depthY];T=[f,this.rx,this.ry,0,0,0,this.leftX,this.depthY];b=[f,this.innerRx,this.innerRy,0,0,0,this.rightInnerX,J];J=[f,this.innerRx,this.innerRy,0,0,0,this.leftInnerX,J];k=[f,this.innerRx,this.innerRy,0,0,1,this.rightInnerX,this.depthY];t=[f,this.innerRx,this.innerRy,0,0,1,this.leftInnerX,this.depthY];this.isDoughnut?(this.topBorderPath=this.moveCmdArr.concat(this.leftPoint,a,e,this.moveCmdArr,this.leftInnerPoint,
b,J),this.topPath=this.moveCmdArr.concat(this.leftPoint,a,e,this.lineCmdArr,this.leftInnerPoint,b,J,this.closeCmdArr),this.innerFrontPath=this.moveCmdArr.concat(this.leftInnerPoint,b,this.lineCmdArr,this.rightInnerDepthPoint,t,this.closeCmdArr),this.innerBackPath=this.moveCmdArr.concat(this.rightInnerPoint,J,this.lineCmdArr,this.leftInnerDepthPoint,k,this.closeCmdArr)):this.topBorderPath=this.topPath=this.moveCmdArr.concat(this.leftPoint,a,e,this.closeCmdArr);this.outerBackPath=this.moveCmdArr.concat(this.leftPoint,
a,this.lineCmdArr,this.rightDepthPoint,T,this.closeCmdArr);this.outerFrontPath=this.moveCmdArr.concat(this.rightPoint,e,this.lineCmdArr,this.leftDepthPoint,h,this.closeCmdArr);this.clipPathforOuter=[d,this.leftX,this.topY,g,this.rightX,this.topY,this.rightX,this.bottomY,this.leftX,this.bottomY,m];this.clipPathforInner=[d,this.leftInnerX,this.topY,g,this.rightInnerX,this.topY,this.rightInnerX,this.bottomY,this.leftInnerX,this.bottomY,m];this.clipPathforNoClip=[d,this.leftInnerX,this.topY,g,this.leftInnerX,
this.bottomY,m]}var ta=this,y=ta.hcLib,ba=y.Raphael,E=window.document,N=y.BLANKSTRING,Ma=y.createTrendLine,j=y.pluck,xa=y.getValidValue,i=y.pluckNumber,G=y.defaultPaletteOptions,Fa=y.getFirstValue,Pa=y.getDefinedColor,ka=y.parseUnsafeString,ha=y.FC_CONFIG_STRING,ua=y.extend2,Na=y.getDashStyle,V=y.toRaphaelColor,Ga=y.toPrecision,Ha=y.stubFN,da=y.hasSVG,za=y.isIE,va=y.each,pa=y.hasTouch?10:3,b="rgba(192,192,192,"+(za?0.002:1.0E-6)+")",c=document.documentMode===8?"visible":"",d="M",g="L",f="A",m="Z",
U=Math,P=U.sin,z=U.cos,I=U.atan2,C=U.round,w=U.min,fa=U.max,la=U.abs,R=U.PI,Va=U.ceil,Y=U.floor,K=U.sqrt,ea=R/180,A=Math.PI,Ra=A/2,ia=2*A,wa=A+Ra,X=y.graphics.getColumnColor,Z=y.getFirstColor,ja=y.setLineHeight,Ba=y.pluckFontSize,Ia=y.getFirstAlpha,ga=y.graphics.getDarkColor,ma=y.graphics.getLightColor,qa=y.graphics.convertColor,Oa=y.COLOR_TRANSPARENT,b="rgba(192,192,192,"+(za?0.002:1.0E-6)+")",Sa=y.POSITION_CENTER,Wa=y.POSITION_TOP,Ua=y.POSITION_BOTTOM,Xa=y.POSITION_RIGHT,Ya=y.POSITION_LEFT,p=y.chartAPI,
Za=y.titleSpaceManager,$a=y.placeLegendBlockBottom,ab=y.placeLegendBlockRight,bb=y.graphics.mapSymbolName,za=p.singleseries,L=y.COMMASTRING,ya=y.ZEROSTRING,Ja=y.ONESTRING,Aa=y.HUNDREDSTRING,Qa=y.PXSTRING,cb=y.COMMASPACE,ra=!/fusioncharts\.com$/i.test(location.hostname);p("column2d",{standaloneInit:!0,creditLabel:ra,rendererId:"cartesian"},p.column2dbase);p("column3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},p.column2d);p("bar2d",{isBar:!0,defaultSeriesType:"bar",
spaceManager:p.barbase},p.column2d);p("bar3d",{defaultSeriesType:"bar3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},p.bar2d);p("line",{standaloneInit:!0,creditLabel:ra,rendererId:"cartesian"},p.linebase);p("area2d",{standaloneInit:!0,creditLabel:ra,rendererId:"cartesian"},p.area2dbase);p("pie2d",{standaloneInit:!0,defaultSeriesType:"pie",defaultPlotShadow:1,sliceOnLegendClick:!0,rendererId:"pie",point:function(a,J,e,h,b){var c,k,t,Ta=b[ha],o=Ta.is3d,n,r,l,d,f=0,g=0,Ka=[];t=i(h.plotborderthickness);
var m=i(t,o?0.1:1),q=(n=i(h.use3dlighting,1))?i(h.radius3d,h["3dradius"],90):100;r=i(h.showzeropies,1);var v=i(h.showpercentintooltip,1),p=i(h.showlabels,1),P=i(h.showvalues,1),A=i(h.showpercentvalues,h.showpercentagevalues,0),F=j(h.tooltipsepchar,h.hovercapsepchar,cb),s=j(h.labelsepchar,F),x=j(h.plotbordercolor,h.piebordercolor),D=b[ha].numberFormatter;l=e.length;var z,w,B=i(h.plotborderdashed,0),H=i(h.plotborderdashlen,5),S=i(h.plotborderdashgap,4);q>100&&(q=100);q<0&&(q=0);if(i(h.showlegend,0))b.legend.enabled=
!0,b.legend.reversed=!Boolean(i(h.reverselegend,0)),J.showInLegend=!0;for(a=0;a<l;a+=1)k=e[a],c=D.getCleanValue(k.value,!0),c===null||!r&&c===0||(Ka.push(k),f+=c);f===0&&(Ka=[]);J.enableRotation=Ka.length>1?i(h.enablerotation,1):0;J.alphaAnimation=i(h.alphaanimation,1);J.is3D=o;J.use3DLighting=n;J.pieYScale=i(h.pieyscale,40);if(J.pieYScale<1)J.pieYScale=1;if(J.pieYScale>=100)J.pieYScale=80;J.pieYScale/=100;J.pieSliceDepth=i(h.pieslicedepth,15);if(J.pieSliceDepth<1)J.pieSliceDepth=1;J.managedPieSliceDepth=
J.pieSliceDepth;if(o&&h.showplotborder!=Ja&&!t)J.showBorderEffect=1;for(a=Ka.length-1;a>=0;a-=1){k=Ka[a];c=D.getCleanValue(k.value,!0);e=ka(j(k.label,k.name,N));n=j(k.color,b.colors[a%b.colors.length]);r=j(k.alpha,h.plotfillalpha);l=j(k.bordercolor,x);d=j(k.borderalpha,h.plotborderalpha,h.pieborderalpha);if(o&&(l||d!==void 0))J.showBorderEffect=0;l=j(l,ma(n,o?90:25)).split(L)[0];d=h.showplotborder==ya?ya:j(d,r,"80");r=j(r,Aa);t={opacity:Math.max(r,d)/100};if(z=Boolean(i(k.issliced,h.issliced,0)))Ta.preSliced=
z;w=i(k.dashed,B)?Na(j(k.dashlen,H),j(k.dashgap,S),m):void 0;J.data.push({showInLegend:e!==N,y:c,name:e,shadow:t,toolText:ka(xa(k.tooltext)),color:this.getPointColor(n,r,q),_3dAlpha:r,borderColor:qa(l,d),borderWidth:m,link:xa(k.link),sliced:z,dashStyle:w,doNotSlice:j(h.enableslicing,Ja)!=Ja});r=D.percentValue(c/f*100);l=D.dataLabels(c)||N;t=v===1?r:l;c=i(k.showlabel,p)===1?e:N;r=(n=i(k.showvalue,P))===1?A===1?r:l:N;k=xa(ka(k.displayvalue));r=k!==void 0&&n?k:r!==N&&c!==N?c+s+r:j(c,r);e=e!=N?e+F+t:
t;k=J.data[g];k.displayValue=r;k.toolText=j(k.toolText,e);g+=1}J.valueTotal=f;b.legend.enabled=h.showlegend==Ja?!0:!1;J.startAngle=i(h.startingangle,0);b.chart.startingAngle=j(Ka.length>1?h.startingangle:0,0);return J},getPointColor:function(a,J,e){var h,b,a=Z(a),J=Ia(J);e<100&&da?(h=Math.floor((100-0.35*e)*85)/100,h=ga(a,h),b=Math.floor((100+e)*50)/100,a=ma(a,b),J={FCcolor:{color:a+L+h,alpha:J+L+J,ratio:e+",100",radialGradient:!0,gradientUnits:"userSpaceOnUse"}}):J={FCcolor:{color:a+L+a,alpha:J+
L+J,ratio:"0,100"}};return J},configureAxis:function(a){var J=0,e=a[ha],h;a.plotOptions.series.dataLabels.style=a.xAxis.labels.style;a.plotOptions.series.dataLabels.color=a.xAxis.labels.style.color;delete e.x;delete e[0];delete e[1];a.chart.plotBorderColor=a.chart.plotBackgroundColor=Oa;e=e.pieDATALabels=[];if(a.series.length===1&&(h=a.series[0].data)&&(J=a.series[0].data.length)>0&&a.plotOptions.series.dataLabels.enabled)for(;J--;)h[J]&&xa(h[J].displayValue)!==void 0&&e.push(h[J].displayValue)},
spaceManager:function(a,J,e,h){var b=a[ha],c=b.is3d,k=this.name,t=b.smartLabel,d=i(b.pieDATALabels&&b.pieDATALabels.length,0),o=0,n=J.chart,r=i(n.managelabeloverflow,0),l=!b.preSliced&&n.enableslicing==ya&&(n.showlegend!=Ja||n.interactivelegend==ya)?0:i(n.slicingdistance,20),f=i(n.pieradius,0),g=i(n.enablesmartlabels,n.enablesmartlabel,1),u=g?i(n.skipoverlaplabels,n.skipoverlaplabel,1):0,m=i(n.issmartlineslanted,1),p=i(n.labeldistance,n.nametbdistance,5),q=i(n.smartlabelclearance,5);e-=a.chart.marginRight+
a.chart.marginLeft;var v=h-(a.chart.marginTop+a.chart.marginBottom),h=Math.min(v,e),P=j(n.smartlinecolor,G.plotFillColor[a.chart.paletteIndex]),M=i(n.smartlinealpha,100),z=i(n.smartlinethickness,0.7),F=a.plotOptions.series.dataLabels,s=F.style,x=i(parseInt(s.lineHeight,10),12),D=a.series[0]||{},A=D.pieYScale,w=D.pieSliceDepth,h=f===0?h*0.15:f,B=0,B=2*h;F.connectorWidth=z;F.connectorPadding=i(n.connectorpadding,5);F.connectorColor=qa(P,M);v-=Za(a,J,e,B<v?v-B:v/2);n.showlegend==Ja&&(j(n.legendposition,
Ua).toLowerCase()!=Xa?v-=$a(a,J,e,v/2,!0):e-=ab(a,J,e/3,v,!0));t.setStyle(s);if(d!==1)for(;d--;)J=t.getOriSize(b.pieDATALabels[d]),o=Math.max(o,J.width);g&&(p=q+l);f===0&&(c?(v-=w,B=Math.min(e/2-o,(v/2-x)/A)-p):B=Math.min(e/2-o,v/2-x)-p,B>=h?h=B:p=Math.max(p-(h-B),l));if(c&&(d=v-2*(h*A+x),w>d))D.managedPieSliceDepth=w-d;a.plotOptions.pie3d.slicedOffset=a.plotOptions.pie.slicedOffset=l;a.plotOptions.pie3d.size=a.plotOptions.pie.size=2*h;a.plotOptions.series.dataLabels.distance=p;a.plotOptions.series.dataLabels.isSmartLineSlanted=
m;a.plotOptions.series.dataLabels.enableSmartLabels=g;a.plotOptions.series.dataLabels.skipOverlapLabels=u;a.plotOptions.series.dataLabels.manageLabelOverflow=r;if(k==="doughnut2d"||k==="doughnut3d")if(k=i(n.doughnutradius,0),d=i(n.use3dlighting,1)?i(n.radius3d,n["3dradius"],50):100,d>100&&(d=100),d<0&&(d=0),n=k===0||k>=h?h/2:k,a.plotOptions.pie3d.innerSize=a.plotOptions.pie.innerSize=2*n,d>0&&da&&(n=parseInt(n/h*100,10),k=(100-n)/2,d=parseInt(k*d/100,10),n=n+L+d+L+2*(k-d)+L+d,a.series[0]&&a.series[0].data)){r=
a.series[0].data;a=0;for(d=r.length;a<d;a+=1)if(k=r[a],k.color.FCcolor)k.color.FCcolor.ratio=n}},creditLabel:ra,eiMethods:{sliceDataItem:function(a){var b=this.jsVars.hcObj,e;if(b&&b.datasets&&(e=b.datasets[0])&&e.data&&e.data[a]&&e.data[a].plot)return b.plotGraphicClick.call(e.data[a].plot)}}},za);p.pie2d.eiMethods.togglePieSlice=p.pie2d.eiMethods.sliceDataItem;p.pie2d.eiMethods.enableSlicingMovement=p.pie2d.eiMethods.enablelink=function(){ta.raiseWarning(this,"1301081430","run","JSRenderer~enablelink()",
"Method deprecated.")};p("pie3d",{defaultSeriesType:"pie3d",rendererId:"pie3d",creditLabel:ra,getPointColor:function(a){return a},defaultPlotShadow:0},p.pie2d);p("doughnut2d",{getPointColor:function(a,b,e){var h,a=Z(a),b=Ia(b);e<100&&da?(h=ga(a,Y((85-0.2*(100-e))*100)/100),a=ma(a,Y((100-0.5*e)*100)/100),b={FCcolor:{color:h+","+a+","+a+","+h,alpha:b+","+b+","+b+","+b,radialGradient:!0,gradientUnits:"userSpaceOnUse",r:e}}):b={FCcolor:{color:a+","+a,alpha:b+","+b,ratio:"0,100"}};return b}},p.pie2d);
p("doughnut3d",{defaultSeriesType:"pie3d",rendererId:"pie3d",getPointColor:p.pie3d,defaultPlotShadow:0},p.doughnut2d);p("pareto2d",{standaloneInit:!0,point:function(a,b,e,h,T){var c,k,t,d,o,n,r,l,f,g,u,p,m,q,v,a=e.length,P=0;n={};m=T.chart.paletteIndex;var M=/3d$/.test(T.chart.defaultSeriesType),w=this.isBar,F=j(360-h.plotfillangle,90),s=i(h.plotborderthickness,1),x=T.chart.useRoundEdges,D=j(h.tooltipsepchar,", "),A=j(h.plotbordercolor,G.plotBorderColor[m]).split(L)[0],z=h.showplotborder==ya?ya:j(h.plotborderalpha,
h.plotfillalpha,Aa),B=T.xAxis,H=i(h.showcumulativeline,1),S=T[ha],O=S.axisGridManager,C=S.x,U=h.showtooltip!=ya,Q=[],I=[],y=i(h.use3dlighting,1),E=T[ha].numberFormatter,fa=i(h.showlinevalues,h.showvalues),R=i(h.plotborderdashed,0),K=i(h.plotborderdashlen,5),la=i(h.plotborderdashgap,4),z=M?h.showplotborder?z:ya:z,A=M?j(h.plotbordercolor,"#FFFFFF"):A;for(p=k=0;k<a;k+=1)if(u=e[k],e[k].vline)O.addVline(B,u,p,T);else if(c=E.getCleanValue(u.value,!0),c!==null)u.value=c,Q.push(u),p+=1;a=Q.length;Q.sort(function(a,
e){return e.value-a.value});if(H)r=i(h.linedashed,0),q=Z(j(h.linecolor,G.plotBorderColor[m])),k=j(h.linealpha,100),l=i(h.linedashlen,5),f=i(h.linedashgap,4),n=i(h.linethickness,2),g={opacity:k/100},v=i(h.drawanchors,h.showanchors),v===void 0&&(v=k!=ya),t=i(h.anchorborderthickness,1),o=i(h.anchorsides,0),d=i(h.anchorradius,3),p=Z(j(h.anchorbordercolor,q)),c=Z(j(h.anchorbgcolor,G.anchorBgColor[m])),e=Ia(j(h.anchoralpha,Aa)),u=Ia(j(h.anchorbgalpha,e))*e/100,r=r?Na(l,f,n):void 0,n={yAxis:1,data:[],type:"line",
color:{FCcolor:{color:q,alpha:k}},lineWidth:n,marker:{enabled:v,fillColor:{FCcolor:{color:c,alpha:u}},lineColor:{FCcolor:{color:p,alpha:e}},lineWidth:t,radius:d,symbol:bb(o),startAngle:j(h.anchorstartangle,90)}};else{if(h.showsecondarylimits!=="1")h.showsecondarylimits="0";if(h.showdivlinesecondaryvalue!=="1")h.showdivlinesecondaryvalue="0"}for(k=0;k<a;k+=1)u=Q[k],c=i(u.showlabel,h.showlabels,1),e=ka(!c?N:Fa(u.label,u.name)),O.addXaxisCat(B,k,k,e),P+=c=u.value,t=j(u.color,T.colors[k%T.colors.length])+
L+(i(h.useplotgradientcolor,1)?Pa(h.plotgradientcolor,G.plotGradientColor[m]):N),d=j(u.alpha,h.plotfillalpha,Aa),o=j(u.ratio,h.plotfillratio),p={opacity:d/100},q=j(u.alpha,z)+N,t=X(t,d,o,F,x,A,q,w,M),b.data.push(ua(this.getPointStub(u,c,e,T),{y:c,shadow:p,color:t[0],borderColor:t[1],borderWidth:s,use3DLighting:y,dashStyle:i(u.dashed,R)==1?Na(K,la,s):"",tooltipConstraint:this.tooltipConstraint})),this.pointValueWatcher(T,c),H&&I.push({value:P,dataLabel:e,tooltext:xa(u.tooltext)});C.catCount=a;S[1]||
(S[1]={});S[1].stacking100Percent=!0;if(H&&P>0){k=0;for(a=I.length;k<a;k+=1)u=I[k],T=b.data[k],c=u.value/P*100,m=E.percentValue(c),h=T.displayValue!==N?m:N,fa==1&&(h=m),fa==0&&(h=N),e=u.dataLabel,m=U?u.tooltext!==void 0?u.tooltext:(e!==N?e+D:N)+m:N,n.data.push({shadow:g,color:n.color,marker:n.marker,y:c,toolText:m,displayValue:h,link:T.link,dashStyle:r});return[b,n]}else return b},defaultSeriesType:"column",isDual:!0,creditLabel:ra,rendererId:"cartesian"},za);p("pareto3d",{defaultSeriesType:"column3d",
defaultPlotShadow:1,is3D:!0},p.pareto2d);p("mscolumn2d",{standaloneInit:!0,creditLabel:ra,rendererId:"cartesian"},p.mscolumn2dbase);p("mscolumn3d",{defaultSeriesType:"column3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},p.mscolumn2d);p("msbar2d",{isBar:!0,defaultSeriesType:"bar",spaceManager:p.barbase},p.mscolumn2d);p("msbar3d",{defaultSeriesType:"bar3d",defaultPlotShadow:1,is3D:!0,defaultZeroPlaneHighlighted:!1},p.msbar2d);p("msline",{standaloneInit:!0,creditLabel:ra,rendererId:"cartesian"},
p.mslinebase);p("msarea",{standaloneInit:!0,creditLabel:ra,rendererId:"cartesian"},p.msareabase);p("stackedcolumn2d",{isStacked:!0},p.mscolumn2d);p("stackedcolumn3d",{isStacked:!0},p.mscolumn3d);p("stackedbar2d",{isStacked:!0},p.msbar2d);p("stackedbar3d",{isStacked:!0},p.msbar3d);p("stackedarea2d",{isStacked:!0,areaAlpha:100,showSum:0},p.msarea);p("marimekko",{isValueAbs:!0,distributedColumns:!0,isStacked:!0,xAxisMinMaxSetter:Ha,postSeriesAddition:function(a,b){var e=a[ha],h=0,T=a.xAxis,c=100/e.marimekkoTotal,
k=[],t=a.series,d=0,o=i(b.chart.plotborderthickness,1),n=a.chart.rotateValues,r=i(b.chart.rotatexaxispercentvalues,0),o=o*-0.5-(o%2+(r?0:4)),l=r?3:0,f=n?270:0,g=ua({},a.plotOptions.series.dataLabels.style),u=parseInt(g.fontSize,10),m=e[0],p=m.stacking100Percent,q=!p,v=e.inCanvasStyle,P=this.numberFormatter,M=b.categories&&b.categories[0]&&b.categories[0].category||[],j=0,F=[],s,x,D,z,A,B,H,w;e.isXYPlot=!0;e.distributedColumns=!0;T.min=0;T.max=100;T.labels.enabled=!1;T.gridLineWidth=0;T.alternateGridColor=
Oa;s=m.stack;b.chart.interactivelegend="0";m=0;for(x=a.xAxis.plotLines.length;m<x;m+=1)if(D=T.plotLines[m],D.isGrid)D.isCat=!0,k[D.value]=D,D._hideLabel=!0;for(m=x=0;m<M.length;m+=1)M[m].vline||(j+=F[x]=P.getCleanValue(M[m].widthpercent||0),x+=1);T=s.floatedcolumn&&s.floatedcolumn[0]||[];if(j===100&&(T&&T.length)!==x)for(;x--;)T[x]||(T[x]={p:null});j=C(j);if(T){z=0;for(x=T.length;z<x;){w=T[z];h+=D=w&&w.p||0;B=j===100?F[z]:D*c;A=d+B/2;H=d+B;for(m=0;m<t.length;m+=1)if(M=a.series[m].data[z],M._FCX=d,
M._FCW=B,p){if(M.y||M.y===0){s=M.y/D*100;M.y=s;if(M.showPercentValues)M.displayValue=this.numberFormatter.percentValue(s);if(M.showPercentInToolTip)M.toolText=M.toolText+parseInt(s*100,10)/100+"%"}if(M.previousY||M.previousY===0)M.previousY=M.previousY/D*100}e.showStackTotal&&a.xAxis.plotLines.push({value:A,width:0,isVline:q,isTrend:!q,_isStackSum:1,zIndex:4,label:{align:Sa,textAlign:f,rotation:n?270:0,style:g,verticalAlign:Wa,offsetScale:q?D<0?w.n:w.p:void 0,offsetScaleIndex:0,y:D<0?n===270?4:u:
-4,x:0,text:P.yAxis(Ga(D,10))}});if(k[z])k[z].value=A,k[z]._weight=B,k[z]._hideLabel=!1;z+=1;e.showXAxisPercentValues&&z<x&&a.xAxis.plotLines.push({value:H,width:0,isVine:!0,label:{align:Sa,textAlign:r?Ya:Sa,rotation:r?270:0,backgroundColor:"#ffffff",backgroundOpacity:1,borderWidth:"1px",borderType:"solid",borderColor:v.color,style:{color:v.color,fontSize:v.fontSize,fontFamily:v.fontFamily,lineHeight:v.lineHeight},verticalAlign:Ua,y:o,x:l,text:this.numberFormatter.percentValue(H)},zIndex:5});d=H}}z=
0;for(x=k.length;z<x;z+=1)if(k[z]&&k[z]._hideLabel)k[z].value=null},defaultSeriesType:"floatedcolumn"},p.stackedcolumn2d);p("msstackedcolumn2d",{series:function(a,b,e){var h,T,c,k,t=b[ha],d=0,o,n;o=[];var r;b.legend.enabled=Boolean(i(a.chart.showlegend,1));if(a.dataset&&a.dataset.length>0){this.categoryAdder(a,b);h=0;for(T=a.dataset.length;h<T;h+=1)if(r=a.dataset[h].dataset){c=0;for(k=r.length;c<k;c+=1,d+=1)o={visible:!!i(r.visible,1),data:[],numColumns:T,columnPosition:h},n=Math.min(t.oriCatTmp.length,
r[c].data&&r[c].data.length),o=this.point(e,o,r[c],a.chart,b,n,d,h),b.series.push(o)}if(this.isDual&&a.lineset&&a.lineset.length>0){c=0;for(k=a.lineset.length;c<k;c+=1,d+=1)o={visible:!!i(a.lineset[c].visible,1),data:[],yAxis:1,type:"line"},e=a.lineset[c],n=Math.min(t.oriCatTmp.length,e.data&&e.data.length),b.series.push(p.msline.point.call(this,"msline",o,e,a.chart,b,n,d))}this.configureAxis(b,a);a.trendlines&&Ma(a.trendlines,b.yAxis,b[ha],!1,this.isBar)}},postSpaceManager:function(a,b,e){var l;
var h=a[ha],T,c,k;if(this.isStacked&&h.showStackTotal&&(T=a.chart,l=(b=a.xAxis)&&b.plotLines,a=l,T=e-T.marginLeft-T.marginRight,e=h.plotSpacePercent,h=h[0].stack,h=h.column&&h.column.length,b=T/(b.max-b.min),b*((1-2*e)/h)>50&&e==0.1)){b=50/b;e=a&&a.length;h=-((h-1)/2)*b;for(k=0;k<e;k+=1)if(c=a[k],c._isStackSum)T=c._catPosition+(h+b*c._stackIndex),c.value=T}}},p.stackedcolumn2d);p("mscombi2d",{standaloneInit:!0,creditLabel:ra,rendererId:"cartesian"},p.mscombibase);p("mscombi3d",{series:p.mscombi2d.series,
eiMethods:function(a){var b={};va(a.split(","),function(a){b[a]=function(){ta.raiseWarning(this,"1301081430","run","JSRenderer~"+a+"()","Method not applicable.")}});return b}("view2D,view3D,resetView,rotateView,getViewAngles,fitToStage")},p.mscolumn3d);p("mscolumnline3d",{},p.mscombi3d);p("stackedcolumn2dline",{isStacked:!0,stack100percent:0},p.mscombi2d);p("stackedcolumn3dline",{isStacked:!0,stack100percent:0},p.mscombi3d);p("mscombidy2d",{isDual:!0,secondarySeriesType:void 0},p.mscombi2d);p("mscolumn3dlinedy",
{isDual:!0,secondarySeriesType:"line"},p.mscolumnline3d);p("stackedcolumn3dlinedy",{isDual:!0,secondarySeriesType:"line"},p.stackedcolumn3dline);p("msstackedcolumn2dlinedy",{isDual:!0,stack100percent:0,secondarySeriesType:"line"},p.msstackedcolumn2d);p("scrollcolumn2d",{postSeriesAddition:p.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},p.mscolumn2d);p("scrollline2d",{postSeriesAddition:p.scrollbase.postSeriesAddition,tooltipConstraint:"plot",
canvasborderthickness:1,avgScrollPointWidth:75},p.msline);p("scrollarea2d",{postSeriesAddition:p.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:75},p.msarea);p("scrollstackedcolumn2d",{postSeriesAddition:function(a,b,e,h){p.base.postSeriesAddition.call(this,a,b,e,h);p.scrollbase.postSeriesAddition.call(this,a,b,e,h)},canvasborderthickness:1,tooltipConstraint:"plot",avgScrollPointWidth:75},p.stackedcolumn2d);p("scrollcombi2d",{postSeriesAddition:p.scrollbase.postSeriesAddition,
tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},p.mscombi2d);p("scrollcombidy2d",{postSeriesAddition:p.scrollbase.postSeriesAddition,tooltipConstraint:"plot",canvasborderthickness:1,avgScrollPointWidth:40},p.mscombidy2d);p("scatter",{standaloneInit:!0,defaultSeriesType:"scatter",defaultZeroPlaneHighlighted:!1,creditLabel:ra},p.scatterbase);p("bubble",{standaloneInit:!0,standaloneInut:!0,defaultSeriesType:"bubble",rendererId:"bubble",point:function(a,b,e,h,T,c,k){if(e.data){var t,
d,o,n,r,l,f,g,m,P,z=!1,q,v,a=p[a],c=e.data,w=c.length,M=i(e.showvalues,T[ha].showValues);o=i(h.bubblescale,1);var A=j(h.negativecolor,"FF0000"),F=T.plotOptions.bubble,s=this.numberFormatter,x=i(e.showregressionline,h.showregressionline,0);F.bubbleScale=o;b.name=xa(e.seriesname);if(i(e.includeinlegend)===0||b.name===void 0)b.showInLegend=!1;o=Boolean(i(e.drawanchors,e.showanchors,h.drawanchors,1));f=j(e.plotfillalpha,e.bubblefillalpha,h.plotfillalpha,Aa);g=i(e.showplotborder,h.showplotborder,1);m=
Z(j(e.plotbordercolor,h.plotbordercolor,"666666"));t=j(e.plotborderthickness,h.plotborderthickness,1);P=j(e.plotborderalpha,h.plotborderalpha,"95");g=g==1?t:0;k=j(e.color,e.plotfillcolor,h.plotfillcolor,T.colors[k%T.colors.length]);b.marker={enabled:o,fillColor:this.getPointColor(k,Aa),lineColor:{FCcolor:{color:m,alpha:P}},lineWidth:g,symbol:"circle"};if(x){b.events={hide:this.hideRLine,show:this.showRLine};var D={sumX:0,sumY:0,sumXY:0,sumXsqure:0,sumYsqure:0,xValues:[],yValues:[]},C=i(e.showyonx,
h.showyonx,1),I=Z(j(e.regressionlinecolor,h.regressionlinecolor,k)),B=i(e.regressionlinethickness,h.regressionlinethickness,1);t=Ia(i(e.regressionlinealpha,h.regressionlinealpha,100));I=qa(I,t)}for(d=0;d<w;d+=1)if(n=c[d])if(t=s.getCleanValue(n.y),q=s.getCleanValue(n.x),v=s.getCleanValue(n.z,!0),t===null)b.data.push({y:null,x:q});else{z=!0;r=Z(j(n.color,n.z<0?A:k));l=j(n.alpha,f);n=a.getPointStub(n,t,q,T,e,M);r=i(h.use3dlighting)===0?r:a.getPointColor(r,l);if(v!==null)F.zMax=F.zMax>v?F.zMax:v,F.zMin=
F.zMin<v?F.zMin:v;b.data.push({y:t,x:q,z:v,displayValue:n.displayValue,toolText:n.toolText,link:n.link,marker:{enabled:o,fillColor:r,lineColor:{FCcolor:{color:m,alpha:P}},lineWidth:g,symbol:"circle"}});this.pointValueWatcher(T,t,q,x&&D)}else b.data.push({y:null});x&&(e={type:"line",color:I,showInLegend:!1,lineWidth:B,enableMouseTracking:!1,marker:{enabled:!1},data:this.getRegressionLineSeries(D,C,w),zIndex:0},b=[b,e])}if(!z)b.showInLegend=!1;return b},postSeriesAddition:function(a,b){a.chart.clipBubbles=
i(b.chart.clipbubbles,1)},getPointStub:function(a,b,e,h,c,d){var h=h[ha],b=b===null?b:h.numberFormatter.dataLabels(b),k,t=h.tooltipSepChar;h.showTooltip?xa(a.tooltext)!==void 0?c=ka(a.tooltext):b===null?c=!1:(h.seriesNameInToolTip&&(k=j(c&&c.seriesname)),c=k?k+t:N,c+=e?e+t:N,c+=b,c+=a.z?t+a.z:N):c=N;e=i(a.showvalue,d,h.showValues)?j(a.displayvalue,a.name,a.label)!==void 0?ka(j(a.displayvalue,a.name,a.label)):b:N;a=xa(a.link);return{displayValue:e,toolText:c,link:a}}},p.scatter);p("ssgrid",{standaloneInit:!0,
defaultSeriesType:"ssgrid",rendererId:"ssgrid",chart:function(a,b){var B;var e=this.containerElement,h=this.dataObj,c=this.chartInstance,h=ua({},h);h.chart=h.chart||h.graph||{};delete h.graph;var d,k,t,f=0,o,n,r=[],l=h.chart,g=h.data,m=g&&g.length,h=this.smartLabel,u=this.numberFormatter,P=e.offsetHeight,z=e.offsetWidth,q={},v=0,w=0,M=(l.palette>0&&l.palette<6?l.palette:i(this.paletteIndex,1))-1,e={_FCconf:{0:{stack:{}},1:{stack:{}},x:{stack:{}},noWrap:!1,marginLeftExtraSpace:0,marginRightExtraSpace:0,
marginBottomExtraSpace:0,marginTopExtraSpace:0,marimekkoTotal:0},chart:{renderTo:e,ignoreHiddenSeries:!1,events:{},spacingTop:0,spacingRight:0,spacingBottom:0,spacingLeft:0,marginTop:0,marginRight:0,marginBottom:0,marginLeft:0,borderRadius:0,borderColor:"#000000",borderWidth:1,defaultSeriesType:"ssgrid",style:{fontFamily:j(l.basefont,"Verdana"),fontSize:Ba(l.basefontsize,20)+Qa,color:j(l.basefontcolor,G.baseFontColor[M]).replace(/^#?([a-f0-9]+)/ig,"#$1")},plotBackgroundColor:Oa},labels:{smartLabel:h},
colors:["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],credits:{href:"http://www.fusioncharts.com?BS=FCHSEvalMark",text:y.CREDIT_STRING,enabled:this.creditLabel},legend:{enabled:!1},series:[],subtitle:{text:N},title:{text:N},tooltip:{enabled:!1},exporting:{buttons:{exportButton:{},printButton:{enabled:!1}}}},A=e[ha],F=e.colors,s=e.colors.length,
x=o=k=v=0,w=f=n=0;t=c.jsVars.cfgStore;c=e.chart;ja(e.chart.style);c.events.click=this.linkClickFN;k=c.toolbar={button:{}};o=k.button;o.scale=i(l.toolbarbuttonscale,1.15);o.width=i(l.toolbarbuttonwidth,15);o.height=i(l.toolbarbuttonheight,15);o.radius=i(l.toolbarbuttonradius,2);o.spacing=i(l.toolbarbuttonspacing,5);o.fill=qa(j(l.toolbarbuttoncolor,"ffffff"));o.labelFill=qa(j(l.toolbarlabelcolor,"cccccc"));o.symbolFill=qa(j(l.toolbarsymbolcolor,"ffffff"));o.hoverFill=qa(j(l.toolbarbuttonhovercolor,
"ffffff"));o.stroke=qa(j(l.toolbarbuttonbordercolor,"bbbbbb"));o.symbolStroke=qa(j(l.toolbarsymbolbordercolor,"9a9a9a"));o.strokeWidth=i(l.toolbarbuttonborderthickness,1);o.symbolStrokeWidth=i(l.toolbarsymbolborderthickness,1);n=o.symbolPadding=i(l.toolbarsymbolpadding,5);o.symbolHPadding=i(l.toolbarsymbolhpadding,n);o.symbolVPadding=i(l.toolbarsymbolvpadding,n);n=k.position=j(l.toolbarposition,"tr").toLowerCase();switch(n){case "tr":case "tl":case "br":case "bl":break;default:n="tr"}o=k.hAlign=(N+
l.toolbarhalign).toLowerCase()==="left"?"l":n.charAt(1);B=k.vAlign=(N+l.toolbarvalign).toLowerCase()==="bottom"?"b":n.charAt(0),n=B;k.hDirection=i(l.toolbarhdirection,o==="r"?-1:1);k.vDirection=i(l.toolbarvdirection,n==="b"?-1:1);k.vMargin=i(l.toolbarvmargin,6);k.hMargin=i(l.toolbarhmargin,10);k.x=i(l.toolbarx,o==="l"?0:a);k.y=i(l.toolbary,n==="t"?0:b);if(j(l.clickurl)!==void 0)c.link=l.clickurl,c.style.cursor="pointer";q.showPercentValues=i(t.showpercentvalues,l.showpercentvalues,0);q.numberItemsPerPage=
j(t.numberitemsperpage,l.numberitemsperpage);q.showShadow=i(t.showshadow,l.showshadow,0);q.baseFont=j(t.basefont,l.basefont,"Verdana");d=Ba(t.basefontsize,l.basefontsize,10);q.baseFontSize=d+Qa;q.baseFontColor=Z(j(t.basefontcolor,l.basefontcolor,G.baseFontColor[M]));q.alternateRowBgColor=Z(j(t.alternaterowbgcolor,l.alternaterowbgcolor,G.altHGridColor[M]));q.alternateRowBgAlpha=j(t.alternaterowbgalpha,l.alternaterowbgalpha,G.altHGridAlpha[M])+N;q.listRowDividerThickness=i(t.listrowdividerthickness,
l.listrowdividerthickness,1);q.listRowDividerColor=Z(j(t.listrowdividercolor,l.listrowdividercolor,G.borderColor[M]));q.listRowDividerAlpha=i(t.listrowdivideralpha,l.listrowdivideralpha,G.altHGridAlpha[M])+15+N;q.colorBoxWidth=i(t.colorboxwidth,l.colorboxwidth,8);q.colorBoxHeight=i(t.colorboxheight,l.colorboxheight,8);q.navButtonRadius=i(t.navbuttonradius,l.navbuttonradius,7);q.navButtonColor=Z(j(t.navbuttoncolor,l.navbuttoncolor,G.canvasBorderColor[M]));q.navButtonHoverColor=Z(j(t.navbuttonhovercolor,
l.navbuttonhovercolor,G.altHGridColor[M]));q.textVerticalPadding=i(t.textverticalpadding,l.textverticalpadding,3);q.navButtonPadding=i(t.navbuttonpadding,l.navbuttonpadding,5);q.colorBoxPadding=i(t.colorboxpadding,l.colorboxpadding,10);q.valueColumnPadding=i(t.valuecolumnpadding,l.valuecolumnpadding,10);q.nameColumnPadding=i(t.namecolumnpadding,l.namecolumnpadding,5);q.borderThickness=i(t.borderthickness,l.borderthickness,1);q.borderColor=Z(j(t.bordercolor,l.bordercolor,G.borderColor[M]));q.borderAlpha=
j(t.borderalpha,l.borderalpha,G.borderAlpha[M])+N;q.bgColor=j(t.bgcolor,l.bgcolor,"FFFFFF");q.bgAlpha=j(t.bgalpha,l.bgalpha,Aa);q.bgRatio=j(t.bgratio,l.bgratio,Aa);q.bgAngle=j(t.bgangle,l.bgangle,ya);c.borderRadius=q.borderThickness/16;c.borderWidth=q.borderThickness;c.borderColor=V({FCcolor:{color:q.borderColor,alpha:q.borderAlpha}});c.backgroundColor={FCcolor:{color:q.bgColor,alpha:q.bgAlpha,ratio:q.bgRatio,angle:q.bgAngle}};c.borderRadius=i(l.borderradius,0);t={fontFamily:q.baseFont,fontSize:q.baseFontSize,
color:q.baseFontColor};ja(t);h.setStyle(t);for(f=0;f<m;f+=1)if(d=g[f],o=u.getCleanValue(d.value),n=ka(Fa(d.label,d.name)),k=Z(j(d.color,F[f%s])),j(d.alpha,l.plotfillalpha,Aa),n!=N||o!=null)r.push({value:o,label:n,color:k}),v+=o,w+=1;for(f=0;f<w;f+=1)d=r[f],o=d.value,d.dataLabel=d.label,d.displayValue=q.showPercentValues?u.percentValue(o/v*100):u.dataLabels(o),g=h.getOriSize(d.displayValue),x=Math.max(x,g.width+q.valueColumnPadding);q.numberItemsPerPage?q.numberItemsPerPage>=w?(q.numberItemsPerPage=
w,o=P/q.numberItemsPerPage,k=w):(u=P,u-=2*(q.navButtonPadding+q.navButtonRadius),k=q.numberItemsPerPage,o=u/k):(v=parseInt(t.lineHeight,10),v+=2*q.textVerticalPadding,v=Math.max(v,q.colorBoxHeight),P/v>=w?(o=P/w,k=w):(u=P,u-=2*(q.navButtonPadding+q.navButtonRadius),k=Math.floor(u/v),o=u/k));n=z-q.colorBoxPadding-q.colorBoxWidth-q.nameColumnPadding-x-q.valueColumnPadding;f=q.colorBoxPadding+q.colorBoxWidth+q.nameColumnPadding;u=j(l.basefont,"Verdana");g=Ba(l.basefontsize,10);M=j(l.basefontcolor,G.baseFontColor[M]);
m=j(l.outcnvbasefont,u);d=Ba(l.outcnvbasefontsize,g);x=d+Qa;l=j(l.outcnvbasefontcolor,M).replace(/^#?([a-f0-9]+)/ig,"#$1");g+=Qa;M=M.replace(/^#?([a-f0-9]+)/ig,"#$1");A.trendStyle=A.outCanvasStyle={fontFamily:m,color:l,fontSize:x};ja(A.trendStyle);A.inCanvasStyle={fontFamily:u,fontSize:g,color:M};e.tooltip.style={fontFamily:u,fontSize:g,lineHeight:void 0,color:M};e.tooltip.shadow=!1;c.height=P;c.width=z;c.rowHeight=o;c.labelX=f;c.colorBoxWidth=q.colorBoxWidth;c.colorBoxHeight=q.colorBoxHeight;c.colorBoxX=
q.colorBoxPadding;c.valueX=q.colorBoxPadding+q.colorBoxWidth+q.nameColumnPadding+n+q.valueColumnPadding;c.valueColumnPadding=q.valueColumnPadding;c.textStyle=t;c.listRowDividerAttr={"stroke-width":q.listRowDividerThickness,stroke:{FCcolor:{color:q.listRowDividerColor,alpha:q.listRowDividerAlpha}}};c.alternateRowColor={FCcolor:{color:q.alternateRowBgColor,alpha:q.alternateRowBgAlpha}};c.navButtonRadius=q.navButtonRadius;c.navButtonPadding=q.navButtonPadding;c.navButtonColor=q.navButtonColor;c.navButtonHoverColor=
q.navButtonHoverColor;c.lineHeight=parseInt(t.lineHeight,10);l=[];P=0;q=!0;for(f=0;f<w&k!=0;f+=1)f%k==0&&(l.push({data:[],visible:q}),q=!1,P+=1),d=r[f],z=h.getSmartText(d.dataLabel,n,o),l[P-1].data.push({label:z.text,originalText:z.tooltext,displayValue:d.displayValue,y:d.value,color:d.color});e.series=l;p.base.parseExportOptions.call(this,e);e.tooltip.enabled=!!e.exporting.enabled;return e},creditLabel:ra},p.base);p("renderer.bubble",{drawPlotBubble:function(a,c){var e=this,h=e.options,d=h.chart,
f=h.plotOptions.series,k=e.paper,t=e.elements,g=a.items,o=a.graphics=a.graphics||[],n=e.xAxis[c.xAxis||0],r=e.yAxis[c.yAxis||0],l=a.data,m=(h.tooltip||{}).enabled!==!1,f=isNaN(+f.animation)&&f.animation.duration||f.animation*1E3,p=c.visible===!1?"hidden":"visible",h=h.plotOptions.bubble,u=h.zMax,h=h.bubbleScale,P=w(e.canvasHeight,e.canvasWidth)/8,u=K(u),z,q,v,A,j,I,F,s,x,D,U=e.layers,y=U.dataset=U.dataset||k.group("dataset-orphan");U.datalabels=U.datalabels||k.group("datalables").insertAfter(y);var U=
U.tracker,B,H,y=y.bubble=y.bubble||k.group("bubble",y);d.clipBubbles&&!y.attrs["clip-rect"]&&y.attr({"clip-rect":t["clip-canvas"]});t=0;for(z=l.length;t<z;t+=1){q=l[t];x=D=H=null;s=q.marker;if(q.y!==null&&s&&s.enabled){v=q.link;d=q.toolText;A=i(q.x,t);j=q.y;F=r.getAxisPosition(j);I=n.getAxisPosition(A);x=K(q.z);B=C(x*P/u)*h;x=k.circle(I,F,0,y).attr({fill:V(s.fillColor),"stroke-width":s.lineWidth,stroke:V(s.lineColor),visibility:p}).animate({r:B||0},f,"easeOut");if(v||m)B<pa&&(B=pa),D=k.circle(I,F,
B,U).attr({cursor:v?"pointer":"",stroke:b,"stroke-width":s.lineWidth,fill:b,ishot:!!v,visibility:p}).tooltip(d).data("link",v).click(function(){var a=this.data("link");a&&e.linkClickFN.call({link:a},e)});g[t]={index:t,x:A,y:j,z:q.z,value:j,graphic:x,dataLabel:H,tracker:D};H=e.drawPlotLineLabel(a,c,t,I,F)}else g[t]={index:t,x:A,y:j};H&&o.push(H);x&&o.push(x);D&&o.push(D)}a.visible=c.visible!==!1;return a}},p["renderer.cartesian"]);p("renderer.ssgrid",{drawGraph:function(){var a=this.options.series,
b=this.elements,e=b.plots,h=a.length,c;if(!e)e=this.plots=this.plots||[],b.plots=e;this.drawSSGridNavButton();for(c=0;c<h;c++){if(!(b=e[c]))e.push(b={items:[],data:a[c].data});a[c].data&&a[c].data.length&&this.drawPlot(b,a[c])}h>1&&this.nenagitePage(0)},drawPlot:function(a){var b=a.data,e=this.paper,h=this.options.chart,c=h.colorBoxHeight,f=h.colorBoxWidth,k=h.colorBoxX,t=h.labelX,m=h.valueX,o=h.rowHeight,n=h.width,r=h.listRowDividerAttr,l=r["stroke-width"],r=V(r.stroke),p=l%2/2,P=h.textStyle,u=this.layers,
u=u.dataset=u.dataset||e.group("dataset-orphan"),h=V(h.alternateRowColor),a=a.items,i=0,z,q,v,w;if(!b||!b.length)b=[];r={stroke:r,"stroke-width":l};w=0;for(l=b.length;w<l;w+=1)if(v=b[w],q=v.y,z=a[w]={index:w,value:q,graphic:null,dataLabel:null,dataValue:null,alternateRow:null,listRowDivider:null,hot:null},!(q===null||q===void 0)){if(w%2===0)z.alternateRow=e.rect(0,i,n,o,0,u).attr({fill:h,"stroke-width":0});q=C(i)+p;z.listRowDivider=e.path([d,0,q,g,n,q],u).attr(r);z.graphic=e.rect(k,i+o/2-c/2,f,c,
0,u).attr({fill:v.color,"stroke-width":0,stroke:"#000000"});q=z.dataLabel=e.text().attr({text:v.label,title:v.originalText||"",x:t,y:i+o/2,fill:P.color,"text-anchor":"start"}).css(P);u.appendChild(q);z=z.dataValue=e.text().attr({text:v.displayValue,title:v.originalText||"",x:m,y:i+o/2,fill:P.color,"text-anchor":"start"}).css(P);u.appendChild(z);i+=o}q=C(i)+p;e.path([d,0,q,g,n,q],u).attr(r)},drawSSGridNavButton:function(a){var a=this,b=a.paper,e=a.options,h=e.chart,c=e.series,f=h.navButtonColor,k=
h.navButtonHoverColor,e=h.navButtonRadius,t=e*0.67,m=h.navButtonPadding+t+(c&&c[0].data&&c[0].data.length*h.rowHeight)+e*0.5,h=h.width-20,o,n,r;if(c.length>1){var l=a.naviigator=b.group("navigation");a.navElePrv=c=b.group(l);o=b.path([d,20,m,g,20+e+t,m-t,20+e,m,20+e+t,m+t,"Z"]).attr({fill:f,"stroke-width":0,cursor:"pointer"});c.appendChild(o);r=b.circle(20+e,m,e).attr({fill:Oa,"stroke-width":0,cursor:"pointer"}).mouseover(function(){o.attr({fill:k,cursor:"pointer"})}).mouseout(function(){o.attr({fill:f})}).click(function(){a.nenagitePage(-1)});
c.appendChild(r);a.navEleNxt=c=b.group(l);n=b.path([d,h,m,g,h-e-t,m-t,h-e,m,h-e-t,m+t,"Z"]).attr({fill:f,"stroke-width":0,cursor:"pointer"});c.appendChild(n);b=b.circle(h-e,m,e).attr({fill:Oa,"stroke-width":0,cursor:"pointer"}).mouseover(function(){n.attr({fill:k})}).mouseout(function(){n.attr({fill:f})}).click(function(){a.nenagitePage(1)});c.appendChild(b)}},nenagitePage:function(a){var b=this.plots,e=b.length,a=(this.currentSeriesIndex||0)+(a||0),c;if(b[a]){for(c=e;c--;)va(b[c].items,function(a){a.graphic&&
a.graphic.hide();a.dataLabel&&a.dataLabel.hide();a.dataValue&&a.dataValue.hide();a.alternateRow&&a.alternateRow.hide();a.listRowDivider&&a.listRowDivider.hide()});va(b[a].items,function(a){a.graphic&&a.graphic.show();a.dataLabel&&a.dataLabel.show();a.dataValue&&a.dataValue.show();a.alternateRow&&a.alternateRow.show();a.listRowDivider&&a.listRowDivider.show()});this.currentSeriesIndex=a;a===0?this.navElePrv.hide():this.navElePrv.show();a===e-1?this.navEleNxt.hide():this.navEleNxt.show()}}},p["renderer.root"]);
Ea.prototype={getArcPath:function(a,b,e,c,d,g,k,t,m,o){return e==d&&c==g?[]:[f,k,t,0,o,m,d,g]},parseColor:function(a,b){var e,c,d,f,k,t,g,o,n,r,l=b/2,m,p,u,P,i;i=3;this.use3DLighting?(e=ga(a,80),c=ga(a,75),t=ma(a,85),g=ma(a,70),o=ma(a,40),n=ma(a,50),ma(a,30),r=ma(a,65),ga(a,85),d=ga(a,69),f=ga(a,75),k=ga(a,95)):(i=10,e=ga(a,90),c=ga(a,87),t=ma(a,93),g=ma(a,87),o=ma(a,80),r=n=ma(a,85),ma(a,80),k=ga(a,85),d=ga(a,75),f=ga(a,80));m=c+L+t+L+g+L+t+L+c;u=b+L+b+L+b+L+b+L+b;p=c+L+a+L+t+L+a+L+c;P=l+L+l+L+l+
L+l+L+l;o=c+L+a+L+o+L+a+L+c;d=f+L+t+L+n+L+t+L+d;f="FFFFFF"+L+"FFFFFF"+L+"FFFFFF"+L+"FFFFFF"+L+"FFFFFF";i=0+L+l/i+L+b/i+L+l/i+L+0;return{frontOuter:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:d,alpha:u,angle:0,ratio:"0,20,15,15,50"}},backOuter:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:o,alpha:P,angle:0,ratio:"0,62,8,8,22"}},frontInner:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,y1:0,x2:this.rightInnerX,
y2:0,color:p,alpha:P,angle:0,ratio:"0,25,5,5,65"}},backInner:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,y1:0,x2:this.rightInnerX,y2:0,color:m,alpha:u,angle:0,ratio:"0,62,8,8,22"}},topBorder:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftX,y1:0,x2:this.rightX,y2:0,color:f,alpha:i,angle:0,ratio:"0,20,15,15,50"}},topInnerBorder:{FCcolor:{gradientUnits:"userSpaceOnUse",x1:this.leftInnerX,y1:0,x2:this.rightInnerX,y2:0,color:f,alpha:i,angle:0,ratio:"0,50,15,15,20"}},top:da?{FCcolor:{gradientUnits:"userSpaceOnUse",
radialGradient:!0,cx:this.cx,cy:this.cy,r:this.rx,fx:this.cx-0.3*this.rx,fy:this.cy+this.ry*1.2,color:r+L+k,alpha:b+L+b,ratio:"0,100"}}:{FCcolor:{gradientUnits:"objectBoundingBox",color:g+L+g+L+t+L+c,alpha:b+L+b+L+b+L+b,angle:-72,ratio:"0,8,15,77"}},bottom:V(qa(a,l)),startSlice:V(qa(e,b)),endSlice:V(qa(e,b))}},rotate:function(a){if(!this.hasOnePoint){for(var b=this.pointElemStore,e=0,c=b.length,d;e<c;e+=1)d=b[e],d=d._confObject,d.start+=a,d.end+=a,this.updateSliceConf(d);this.refreshDrawing()}},refreshDrawing:function(){return function(){var a=
this.slicingWallsArr,b=0,e,c=a.length,d,f,k,t,g=this.slicingWallsFrontGroup,o=this.slicingWallsBackGroup;a:{var n=a[0]&&a[0]._conf.index,r,l;t=n<=A;d=1;for(e=a.length;d<e;d+=1)if(l=a[d]._conf.index,r=l<=A,r!=t||l<n)break a;d=0}for(;b<c;b+=1,d+=1)d===c&&(d=0),e=a[d],t=e._conf.index,t<Ra?g.appendChild(e):t<=A?(f?e.insertBefore(f):g.appendChild(e),f=e):t<wa?(k?e.insertBefore(k):o.appendChild(e),k=e):o.appendChild(e)}}(),updateSliceConf:function(a,b){var e=this.getArcPath,c=a.start,p=a.end,i=sa(c),k=
sa(p),t,w,o,n,r,l,j,aa,u,I,U,q,v,C,M,y,F=this.cx,s=this.cy,x=this.rx,D=this.ry,E=x+(da?-1:2),L=D+(da?-1:2),B=this.innerRx,H=this.innerRy,S=this.depth,O=this.depthY,fa=a.elements,R,Q,ca,K;t=z(i);w=P(i);o=z(k);n=P(k);r=F+x*t;l=s+D*w;j=F+E*t;aa=s+L*w;R=l+S;Q=F+x*o;ca=s+D*n;u=F+E*o;I=s+L*n;K=ca+S;this.isDoughnut?(U=F+B*t,q=s+H*w,M=q+S,v=F+B*o,C=s+H*n,y=C+S,a.startSlice=[d,r,l,g,r,R,U,M,U,q,m],a.endSlice=[d,Q,ca,g,Q,K,v,y,v,C,m]):(a.startSlice=[d,r,l,g,r,R,F,O,F,s,m],a.endSlice=[d,Q,ca,g,Q,K,F,O,F,s,m]);
if(da){e=(i>k?ia:0)+k-i;a.clipTopPath=this.isDoughnut?[d,r,l,f,x,D,0,e>A?1:0,1,Q,ca,g,v,C,f,B,H,0,e>A?1:0,0,U,q,m]:[d,r,l,f,x,D,0,e>A?1:0,1,Q,ca,g,this.cx,this.cy,m];a.clipOuterFrontPath1=this.clipPathforNoClip;a.clipTopBorderPath=[d,j,aa,f,E,L,0,e>A?1:0,1,u,I,g,Q,ca,Q,ca+1,f,x,D,0,e>A?1:0,0,r,l+1,g,r,l,m];if(c!=p)if(i>k)if(i<A){if(a.clipOuterFrontPath=[d,this.rightX,s,f,x,D,0,0,1,Q,ca,"v",S,f,x,D,0,0,0,this.rightX,s+S,m],a.clipOuterFrontPath1=[d,this.leftX,s,f,x,D,0,0,0,r,l,"v",S,f,x,D,0,0,1,this.leftX,
s+S,m],a.clipOuterBackPath=[d,this.rightX,s,f,x,D,0,1,0,this.leftX,s,"v",S,f,x,D,0,1,1,this.rightX,s+S,m],this.isDoughnut)a.clipInnerBackPath=[d,this.rightInnerX,s,f,B,H,0,1,0,this.leftInnerX,s,"v",S,f,B,H,0,1,1,this.rightInnerX,s+S,m],a.clipInnerFrontPath=[d,this.rightInnerX,s,f,B,H,0,0,1,v,C,"v",S,f,B,H,0,0,0,this.rightInnerX,s+S,m,d,this.leftInnerX,s,f,B,H,0,0,0,U,q,"v",S,f,B,H,0,0,1,this.leftInnerX,s+S,m]}else if(k>A){if(a.clipOuterFrontPath=[d,this.rightX,s,f,x,D,0,1,1,this.leftX,s,"v",S,f,x,
D,0,1,0,this.rightX,s+S,m],a.clipOuterBackPath=[d,this.leftX,s,f,x,D,0,0,1,Q,ca,"v",S,f,x,D,0,0,0,this.leftX,s+S,m,d,this.rightX,s,f,x,D,0,0,0,r,l,"v",S,f,x,D,0,0,1,this.rightX,s+S,m],this.isDoughnut)a.clipInnerFrontPath=[d,this.rightInnerX,s,f,B,H,0,1,1,this.leftInnerX,s,"v",S,f,B,H,0,1,0,this.rightInnerX,s+S,m],a.clipInnerBackPath=[d,this.leftInnerX,s,f,B,H,0,0,1,v,C,"v",S,f,B,H,0,0,0,this.leftInnerX,s+S,m,d,this.rightInnerX,s,f,B,H,0,0,0,U,q,"v",S,f,B,H,0,0,1,this.rightInnerX,s+S,m]}else{if(a.clipOuterFrontPath=
[d,this.rightX,s,f,x,D,0,0,1,Q,ca,"v",S,f,x,D,0,0,0,this.rightX,s+S,m],a.clipOuterBackPath=[d,r,l,f,x,D,0,0,1,this.rightX,s,"v",S,f,x,D,0,0,0,r,R,m],this.isDoughnut)a.clipInnerFrontPath=[d,this.rightInnerX,s,f,B,H,0,0,1,v,C,"v",S,f,B,H,0,0,0,this.rightInnerX,s+S,m],a.clipInnerBackPath=[d,U,q,f,B,H,0,0,1,this.rightInnerX,s,"v",S,f,B,H,0,0,0,U,M,m]}else if(i<A)if(k>A){if(a.clipOuterFrontPath=[d,r,l,f,x,D,0,0,1,this.leftX,s,"v",S,f,x,D,0,0,0,r,R,m],a.clipOuterBackPath=[d,this.leftX,s,f,x,D,0,0,1,Q,ca,
"v",S,f,x,D,0,0,0,this.leftX,s+S,m],this.isDoughnut)a.clipInnerFrontPath=[d,U,q,f,B,H,0,0,1,this.leftInnerX,s,"v",S,f,B,H,0,0,0,U,M,m],a.clipInnerBackPath=[d,this.leftInnerX,s,f,B,H,0,0,1,v,C,"v",S,f,B,H,0,0,0,this.leftInnerX,s+S,m]}else{if(a.clipOuterFrontPath=[d,r,l,f,x,D,0,0,1,Q,ca,"v",S,f,x,D,0,0,0,r,R,m],a.clipOuterBackPath=this.clipPathforNoClip,this.isDoughnut)a.clipInnerFrontPath=[d,U,q,f,B,H,0,0,1,v,C,"v",S,f,B,H,0,0,0,U,M,m],a.clipInnerBackPath=this.clipPathforNoClip}else{if(a.clipOuterFrontPath=
this.clipPathforNoClip,a.clipOuterBackPath=[d,r,l,f,x,D,0,0,1,Q,ca,"v",S,f,x,D,0,0,0,r,R,m],this.isDoughnut)a.clipInnerFrontPath=this.clipPathforNoClip,a.clipInnerBackPath=[d,U,q,f,B,H,0,0,1,v,C,"v",S,f,B,H,0,0,0,U,M,m]}else a.clipOuterFrontPath=a.clipOuterBackPath=a.clipInnerBackPath=a.clipInnerFrontPath=this.clipPathforNoClip;if(!b){a.elements.startSlice._conf.index=i;a.elements.endSlice._conf.index=k;a.elements.frontOuter._conf.index=Da(k,i);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=
i,a.elements.frontOuter1.attr("litepath",[a.clipOuterFrontPath1]);a.thisElement.attr("litepath",[a.clipTopPath]);a.elements.bottom.attr("litepath",[a.clipTopPath]);a.elements.bottomBorder.attr("litepath",[a.clipTopPath]);a.elements.topBorder&&a.elements.topBorder.attr("litepath",[a.clipTopBorderPath]);a.elements.frontOuter.attr("litepath",[a.clipOuterFrontPath]);a.elements.backOuter.attr("litepath",[a.clipOuterBackPath]);if(this.isDoughnut)a.elements.backInner.attr("litepath",[a.clipInnerBackPath]),
a.elements.frontInner.attr("litepath",[a.clipInnerFrontPath]),a.elements.backInner._conf.index=Da(k,i);this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr("litepath",[a.startSlice]).show(),a.elements.endSlice.attr("litepath",[a.endSlice]).show())}}else{j=this.moveCmdArr;aa=this.lineCmdArr;u=this.closeCmdArr;var la=this.centerPoint;I=this.leftPoint;var E=this.topPoint,L=this.rightPoint,S=this.bottomPoint,N=this.leftDepthPoint,Y=this.rightDepthPoint;
t=this.leftInnerPoint;w=this.rightInnerPoint;o=this.leftInnerDepthPoint;n=this.rightInnerDepthPoint;a.clipOuterFrontPath1=[];if(c!=p){if(i>k?i<A?(c=e(F,s,r,l,this.leftX,s,x,D,1,0),p=e(F,s,this.leftX,s,this.rightX,s,x,D,1,0),ca=e(F,s,this.rightX,s,Q,ca,x,D,1,0),a.clipOuterBackPath=j.concat(I,p,aa,Y,e(F,O,this.rightX,O,this.leftX,O,x,D,0,0),u),a.clipOuterFrontPath1=j.concat([r,l],c,aa,N,e(F,O,this.leftX,O,r,R,x,D,0,0),u),a.clipOuterFrontPath=j.concat(L,ca,aa,[Q,K],e(F,O,Q,K,this.rightX,O,x,D,0,0),u),
a.clipTopBorderPath=j.concat([r,l],c,p,ca),this.isDoughnut?(r=e(F,s,v,C,this.rightInnerX,s,B,H,0,0),l=e(F,s,this.rightInnerX,s,this.leftInnerX,s,B,H,0,0),q=e(F,s,this.leftInnerX,s,U,q,B,H,0,0),a.clipInnerBackPath=j.concat(w,l,aa,o,e(F,O,this.leftInnerX,O,this.rightInnerX,O,B,H,1,0),u),a.clipInnerFrontPath=j.concat(t,q,aa,[U,M],e(F,O,U,M,this.leftInnerX,O,B,H,1,0),u,j,[v,C],r,aa,n,e(F,O,this.rightInnerX,O,v,y,B,H,1,0),u),a.clipTopPath=a.clipTopBorderPath.concat(aa,[v,C],r,l,q,u),a.clipTopBorderPath=
a.clipTopBorderPath.concat(j,[v,C],r,l,q)):a.clipTopPath=a.clipTopBorderPath.concat(aa,la,u)):k>A?(c=e(F,s,r,l,this.rightX,s,x,D,1,0),p=e(F,s,this.rightX,s,this.leftX,s,x,D,1,0),ca=e(F,s,this.leftX,s,Q,ca,x,D,1,0),a.clipOuterFrontPath=j.concat(L,p,aa,N,e(F,O,this.leftX,O,this.rightX,O,x,D,0,0),u),a.clipOuterBackPath=j.concat([r,l],c,aa,Y,e(F,O,this.rightX,O,r,R,x,D,0,0),u,j,I,ca,aa,[Q,K],e(F,O,Q,K,this.leftX,O,x,D,0,0),u),a.clipTopBorderPath=j.concat([r,l],c,p,ca),this.isDoughnut?(r=e(F,s,v,C,this.leftInnerX,
s,B,H,0,0),l=e(F,s,this.leftInnerX,s,this.rightInnerX,s,B,H,0,0),q=e(F,s,this.rightInnerX,s,U,q,B,H,0,0),a.clipInnerFrontPath=j.concat(t,l,aa,n,e(F,O,this.rightInnerX,O,this.leftInnerX,O,B,H,1,0),u),a.clipInnerBackPath=j.concat(w,q,aa,[U,M],e(F,O,U,M,this.rightInnerX,O,B,H,1,0),u,j,[v,C],r,aa,o,e(F,O,this.leftInnerX,O,v,y,B,H,1,0),u),a.clipTopPath=a.clipTopBorderPath.concat(aa,[v,C],r,l,q,u),a.clipTopBorderPath=a.clipTopBorderPath.concat(j,[v,C],r,l,q)):a.clipTopPath=a.clipTopBorderPath.concat(aa,
la,u)):(c=e(F,s,r,l,this.rightX,s,x,D,1,0),p=e(F,s,this.rightX,s,Q,ca,x,D,1,0),a.clipOuterFrontPath=j.concat(L,p,aa,[Q,K],e(F,O,Q,K,this.rightX,O,x,D,0,0),u),a.clipOuterBackPath=j.concat([r,l],c,aa,Y,e(F,O,this.rightX,O,r,R,x,D,0,0),u),a.clipTopBorderPath=j.concat([r,l],c,p),this.isDoughnut?(r=e(F,s,v,C,this.rightInnerX,s,B,H,0,0),l=e(F,s,this.rightInnerX,s,U,q,B,H,0,0),a.clipInnerFrontPath=j.concat([v,C],r,aa,n,e(F,O,this.rightInnerX,O,v,y,B,H,1,0),u),a.clipInnerBackPath=j.concat(w,l,aa,[U,M],e(F,
O,U,M,this.rightInnerX,O,B,H,1,0),u),a.clipTopPath=a.clipTopBorderPath.concat(aa,[v,C],r,l,u),a.clipTopBorderPath=a.clipTopBorderPath.concat(j,[v,C],r,l)):a.clipTopPath=a.clipTopBorderPath.concat(aa,la,u)):i<A?k>A?(c=e(F,s,r,l,this.leftX,s,x,D,1,0),p=e(F,s,this.leftX,s,Q,ca,x,D,1,0),a.clipOuterBackPath=j.concat(I,p,aa,[Q,K],e(F,O,Q,K,this.leftX,O,x,D,0,0),u),a.clipOuterFrontPath=j.concat([r,l],c,aa,N,e(F,O,this.leftX,O,r,R,x,D,0,0),u),a.clipTopBorderPath=j.concat([r,l],c,p),this.isDoughnut?(r=e(F,
s,v,C,this.leftInnerX,s,B,H,0,0),l=e(F,s,this.leftInnerX,s,U,q,B,H,0,0),a.clipInnerBackPath=j.concat([v,C],r,aa,o,e(F,O,this.leftInnerX,O,v,y,B,H,1,0),u),a.clipInnerFrontPath=j.concat(t,l,aa,[U,M],e(F,O,U,M,this.leftInnerX,O,B,H,1,0),u),a.clipTopPath=a.clipTopBorderPath.concat(aa,[v,C],r,l,u),a.clipTopBorderPath=a.clipTopBorderPath.concat(j,[v,C],r,l)):a.clipTopPath=a.clipTopBorderPath.concat(aa,la,u)):(c=e(F,s,r,l,Q,ca,x,D,1,0),a.clipOuterBackPath=j.concat([r,l]),a.clipTopBorderPath=a.clipOuterBackPath.concat(c),
a.clipOuterFrontPath=a.clipTopBorderPath.concat(aa,[Q,K],e(F,O,Q,K,r,R,x,D,0,0),u),this.isDoughnut?(r=e(F,s,v,C,U,q,B,H,0,0),a.clipInnerBackPath=j.concat([v,C]),a.clipTopPath=a.clipTopBorderPath.concat(aa,[v,C],r,u),a.clipTopBorderPath=a.clipTopBorderPath.concat(j,[v,C],r),a.clipInnerFrontPath=a.clipInnerBackPath.concat(r,aa,[U,M],e(F,O,U,M,v,y,B,H,1,0),u)):a.clipTopPath=a.clipTopBorderPath.concat(aa,la,u)):(c=e(F,s,r,l,Q,ca,x,D,1,0),a.clipOuterFrontPath=j.concat([r,l]),a.clipTopBorderPath=a.clipOuterFrontPath.concat(c),
a.clipOuterBackPath=a.clipTopBorderPath.concat(aa,[Q,K],e(F,O,Q,K,r,R,x,D,0,0),u),this.isDoughnut?(r=e(F,s,v,C,U,q,B,H,0,0),a.clipInnerFrontPath=j.concat([v,C]),a.clipTopPath=a.clipTopBorderPath.concat(aa,[v,C],r,u),a.clipTopBorderPath=a.clipTopBorderPath.concat(a.clipInnerFrontPath,r),a.clipInnerBackPath=a.clipInnerFrontPath.concat(r,aa,[U,M],e(F,O,U,M,v,y,B,H,1,0),u)):a.clipTopPath=a.clipTopBorderPath.concat(aa,la,u)),c=j.concat(I,aa,L),r=j.concat(E,aa,S),a.clipTopPath=a.clipTopPath.concat(c,r),
a.clipOuterFrontPath=a.clipOuterFrontPath.concat(c),a.clipOuterFrontPath1=a.clipOuterFrontPath1.concat(c),a.clipOuterBackPath=a.clipOuterBackPath.concat(c),this.isDoughnut)r=j.concat(t,aa,w),a.clipInnerFrontPath=a.clipInnerFrontPath.concat(r),a.clipInnerBackPath=a.clipInnerBackPath.concat(r)}else if(a.clipTopPath=a.clipOuterFrontPath=a.clipOuterBackPath=[],this.isDoughnut)a.clipInnerFrontPath=a.clipInnerBackPath=[];if(!b){a.elements.startSlice._conf.index=i;a.elements.endSlice._conf.index=k;a.elements.frontOuter._conf.index=
Da(k,i);if(a.elements.frontOuter1)a.elements.frontOuter1._conf.index=i,fa.frontOuter1.attr({path:a.clipOuterFrontPath1});a.thisElement.attr({path:a.clipTopPath});fa.topBorder.attr({path:a.clipTopBorderPath});fa.bottom.attr({path:a.clipTopPath});fa.bottomBorder.attr({path:a.clipTopBorderPath});fa.frontOuter.attr({path:a.clipOuterFrontPath});fa.backOuter.attr({path:a.clipOuterBackPath});this.isDoughnut&&(fa.frontInner.attr({path:a.clipInnerFrontPath}),fa.backInner.attr({path:a.clipInnerBackPath}));
this.hasOnePoint?(a.elements.startSlice.hide(),a.elements.endSlice.hide()):(a.elements.startSlice.attr({path:a.startSlice}).show(),a.elements.endSlice.attr({path:a.endSlice}).show())}}},createSlice:function(){var a={stroke:!0,strokeWidth:!0,"stroke-width":!0,dashstyle:!0,"stroke-dasharray":!0,translateX:!0,translateY:!0,"stroke-opacity":!0,transform:!0,fill:!0,opacity:!0,ishot:!0,start:!0,end:!0,cursor:!0},b=function(b,e){var c,d,h=this,f=h._confObject,l,g=f.elements,m,p,i=f.pie3DManager;typeof b===
"string"&&e!==void 0&&e!==null&&(c=b,b={},b[c]=e);if(!b||typeof b==="string")h=h._attr(b);else{if(b.cx!==void 0)b.start=b.cx;if(b.cy!==void 0)b.end=b.cy;for(c in b)if(d=b[c],a[c])if(f[c]=d,c==="ishot"||c==="cursor"){l={};l[c]=d;for(m in g)g[m].attr(l);h._attr(l)}else if(c==="transform"){for(m in g)g[m].attr({transform:b[c]});h._attr({transform:b[c]})}else if(c==="stroke"||c==="strokeWidth"||c==="stroke-width"||c==="dashstyle"||c==="stroke-dasharray")l={},l[c]=d,g.topBorder&&g.topBorder.attr(l),g.startSlice.attr(l),
g.endSlice.attr(l),g.bottomBorder.attr(l);else{if(c!=="fill"&&(c==="start"||c==="end"))p=!0}else h._attr(c,d);p&&(i.updateSliceConf(f),i.refreshDrawing())}return h},e=function(a,b,c,e){var h=this._confObject.elements,d;for(d in h)if(c)h[d].drag(b,c,e);else h[d].on(a,b);return c?this.drag(b,c,e):this._on(a,b)},c=function(){var a=this._confObject.elements,b;for(b in a)a[b].hide();return this._hide()},d=function(){var a=this._confObject.elements,b;for(b in a)a[b].show();return this._show()},f=function(){var a=
this._confObject,b=a.elements,c;for(c in b)b[c].destroy();da&&(a.clipTop.destroy(),a.clipOuterFront.destroy(),a.clipOuterBack.destroy(),a.clipOuterFront1&&a.clipOuterFront1.destroy(),a.clipInnerFront&&a.clipInnerFront.destroy(),a.clipInnerBack&&a.clipInnerBack.destroy());return this._destroy()};return function(a,g,m,o,n,r,l,p,i){var u=this.renderer,m=this.parseColor(m,o),j,a={start:a,end:g,elements:{},pie3DManager:this},g=this.slicingWallsArr,o=a.elements,P,q=da?"litepath":"path";this.updateSliceConf(a,
!0);if(da){j={fill:V(m.top),"stroke-width":0};if(i!==1)j.stroke=n,j["stroke-width"]=r;j=u[q](a.clipTopPath,this.topGroup).attr(j);if(i)o.topBorder=u[q](a.clipTopBorderPath,this.topGroup).attr({fill:V(m.topBorder),"stroke-width":0})}else j=u[q](a.clipTopPath,this.topGroup).attr({fill:V(m.top),"stroke-width":0}),o.topBorder=u[q](a.clipTopBorderPath,this.topGroup).attr({stroke:n,"stroke-width":r});o.bottom=u[q](a.clipTopPath,this.bottomBorderGroup).attr({fill:V(m.bottom),"stroke-width":0});o.bottomBorder=
u[q](da?a.clipTopPath:a.clipTopBorderPath,this.bottomBorderGroup).attr({stroke:n,"stroke-width":r});o.frontOuter=u[q](a.clipOuterFrontPath,this.slicingWallsFrontGroup).attr({fill:V(m.frontOuter),"stroke-width":0});o.backOuter=u[q](a.clipOuterBackPath,this.outerBackGroup).attr({fill:V(m.backOuter),"stroke-width":0});o.startSlice=u[q](a.startSlice,this.slicingWallsFrontGroup).attr({fill:V(m.startSlice),stroke:n,"stroke-width":r});o.endSlice=u[q](a.endSlice,this.slicingWallsFrontGroup).attr({fill:V(m.endSlice),
stroke:n,"stroke-width":r});n=sa(a.start);r=sa(a.end);i=(n>r?ia:0)+r-n;if(i>A&&(o.frontOuter1=u[q](a.clipOuterFrontPath1,this.slicingWallsFrontGroup).attr({fill:V(m.frontOuter),"stroke-width":0}),o.frontOuter1._conf={index:n,isStart:0.5,pIndex:l},da))a.clipOuterFront1=a.clipOuterFrontPath1;o.frontOuter._conf={index:Da(r,n),isStart:0.5,pIndex:l};o.startSlice._conf={index:n,isStart:0,pIndex:l};o.endSlice._conf={index:r,isStart:1,pIndex:l};this.hasOnePoint&&(o.startSlice.hide(),o.endSlice.hide());this.isDoughnut?
(o.frontInner=u[q](a.clipInnerFrontPath,this.innerFrontGroup).attr({fill:V(m.frontInner),"stroke-width":0}),o.backInner=u[q](a.clipInnerBackPath,this.innerBackGroup).attr({fill:V(m.backInner),"stroke-width":0}),o.backInner._conf={index:Da(r,n),isStart:0.5,pIndex:l},i>A?da?g.push(o.startSlice,o.frontOuter1,o.frontOuter,o.backInner,o.endSlice):g.push(o.startSlice,o.frontOuter1,o.frontOuter,o.endSlice):da?g.push(o.startSlice,o.frontOuter,o.backInner,o.endSlice):g.push(o.startSlice,o.frontOuter,o.endSlice)):
i>A?g.push(o.startSlice,o.frontOuter1,o.frontOuter,o.endSlice):g.push(o.startSlice,o.frontOuter,o.endSlice);if(p!==void 0){for(P in o)o[P].tooltip(p);j.tooltip(p)}if(da&&(a.clipTop=a.clipTopPath,a.clipOuterFront=a.clipOuterFrontPath,a.clipOuterBack=a.clipOuterBackPath,this.isDoughnut))a.clipInnerFront=a.clipInnerFrontPath,a.clipInnerBack=a.clipInnerBackPath;j._confObject=a;a.thisElement=j;j._destroy=j.destroy;j.destroy=f;j._show=j.show;j.show=d;j._hide=j.hide;j.hide=c;j._on=j.on;j.on=e;j._attr=j.attr;
j.attr=b;this.pointElemStore.push(j);return j}}()};Ea.prototype.constructor=Ea;p("renderer.pie3d",{type:"pie3d",translate:function(){var a=0,b=this.options,c=b.series[0],d=b.plotOptions.series.dataLabels,f=b.plotOptions.pie3d,g=j(c.startAngle,0)%360,k=c.managedPieSliceDepth,m=c.slicedOffset=f.slicedOffset,p=this.canvasWidth,o=this.canvasHeight,n=[this.canvasLeft+p*0.5,this.canvasTop+o*0.5-k*0.5],r,l,A,I,u,b=c.data,y,K=w(p,o),q,v,L,M=d.distance,R=c.pieYScale,F=c.pieSliceDepth,s=c.slicedOffsetY=m*R;
n.push(f.size,f.innerSize||0);n=W(n,function(a,b){return(q=/%$/.test(a))?[p,o-k,K,K][b]*parseInt(a,10)/100:a});n[2]/=2;n[3]/=2;n.push(n[2]*R);n.push((n[2]+n[3])/2);n.push(n[5]*R);c.getX=function(a,b){A=U.asin((a-n[1])/(n[2]+M));return n[0]+(b?-1:1)*z(A)*(n[2]+M)};c.center=n;va(b,function(b){a+=b.y});c.labelsRadius=n[2]+M;c.labelsRadiusY=c.labelsRadius*R;c.quadrantHeight=(o-k)/2;c.quadrantWidth=p/2;I=-g*ea;I=C(I*1E3)/1E3;u=I+ia;f=i(parseInt(d.style.fontSize,10),10)+4;c.maxLabels=Y(c.quadrantHeight/
f);c.labelFontSize=f;c.connectorPadding=i(d.connectorPadding,5);c.isSmartLineSlanted=j(d.isSmartLineSlanted,!0);c.connectorWidth=i(d.connectorWidth,1);c.enableSmartLabels=d.enableSmartLabels;if(!c.pie3DManager)c.pie3DManager=new Ea(n[0],n[1],n[2],n[3],R,F,this.layers.dataset,this.paper,c.data.length===1,c.use3DLighting);va(b,function(b){r=I;y=a?b.y/a:0;I=C((I+y*ia)*1E3)/1E3;I>u&&(I=u);l=I;b.shapeArgs={start:C(r*1E3)/1E3,end:C(l*1E3)/1E3};b.centerAngle=A=(l+r)/2%ia;b.slicedTranslation=[C(z(A)*m),C(P(A)*
s)];v=z(A)*n[2];c.radiusY=L=P(A)*n[4];b.tooltipPos=[n[0]+v*0.7,n[1]+L];b.percentage=y*100;b.total=a})},drawPlotPie3d:function(a,b){this.translate();var c=this,d=a.items,f=a.data,g=c.options,k=g.plotOptions,m=k.series,p=c.layers,o=c.elements.plots[0],n=c.datasets[0],k=k.series.dataLabels,r=m.dataLabels.style,m=i(a.moveDuration,m.animation.duration),l=c.paper,g=(g=g.tooltip||{})&&g.enabled!==!1,j,w=n.slicedOffset,u=n.slicedOffsetY,A=c.plotGraphicClick,C=c.plotDragMove,q=c.plotDragStart,v=c.plotDragEnd,
U=c.plotMouseDown,I=c.plotMouseUp,y=!!c.datasets[0].enableRotation,F=b.showBorderEffect,s,x,D,R,K,B,H,S,O,L,fa;if(!f||!f.length)f=[];o.singletonCase=f.length==1;o.chartPosition=Ca(c.container);o.pieCenter=n.center;o.timerThreshold=30;for(fa=-1;++fa<f.length;)if(x=f[fa],D=x.y,R=x.displayValue,B=x.sliced,L=x.shapeArgs,S=x.centerAngle,j=x.toolText,H=(K=!!x.link)||y||!x.doNotSlice,!(D===null||D===void 0))if(!(s=d[fa])){b.data[fa].plot=s=d[fa]={chart:c,index:fa,seriesData:o,value:D,angle:S,link:x.link,
shapeArgs:L,slicedX:B&&!o.singletonCase?z(S)*w:0,slicedY:B&&!o.singletonCase?P(S)*u:0,sliced:B,labelText:R,graphic:n.pie3DManager.createSlice(L.start,L.end,x.color,x._3dAlpha,x.borderColor,x.borderWidth,fa,g?j:"",F)};b.data[fa].legendClick=function(a){return function(){c.legendClick(null,c,a)}}(fa);s.graphic.plotItem=s;s.transX=z(S)*w;s.transY=P(S)*u;s.slicedTranslation="t"+s.transX+","+s.transY;s.graphic.attr({transform:"t"+s.slicedX+","+s.slicedY,ishot:H,cursor:K?"pointer":""});if(!x.doNotSlice)s.graphic.on("click",
function(a){return function(){A.call(a)}}(s));s.graphic.on("drag",function(a){return function(b,c,e,d,h){C.call(a,b,c,e,d,h)}}(s),function(a){return function(b,c,e){q.call(a,b,c,e)}}(s),function(a){return function(){v.call(a)}}(s));s.graphic.on("mousedown",function(a){return function(){U.call(a)}}(s));s.graphic.on("mouseup",function(a){return function(){I.call(a)}}(s));if(R!==void 0&&(s.dataLabel=l.text(p.dataset).css(r).attr({text:R,title:x.originalText||"",fill:r.color||"#000000",visibility:"hidden",
ishot:H,cursor:K?"pointer":""}),s.dataLabel.click(A,s),s.dataLabel.mousedown(U,s),s.dataLabel.mouseup(I,s),k.distance>0&&(O=k.connectorWidth)&&k.enableSmartLabels))s.connector=l.path("M 0 0 l 0 0",p.dataset).attr({"stroke-width":O,stroke:k.connectorColor||"#606060",visibility:"hidden",ishot:H,cursor:K?"pointer":""}),s.connector.click(A,s),s.connector.mousedown(U,s),s.connector.mouseup(I,s)}n.pie3DManager.refreshDrawing();m>0?c.animate(d,m):c.placeDataLabels(!1,d)},rotate:function(a){var b=this.datasets[0],
c=this.elements.plots[0].items,d=b.slicedOffset,f=b.slicedOffsetY,g=b.startAngle,k,a=a||-b._lastAngle;k=(a-g)%360;b.startAngle=i(a,b.startAngle)%360;k=-(k*R)/180;b.pie3DManager&&b.pie3DManager.rotate(k);va(c,function(a){var b=a.graphic,c=a.shapeArgs,c={start:c.start+=k,end:c.end+=k},e=a.angle=sa((c.start+c.end)/2),c=a.sliced,g=z(e),e=P(e);a.slicedTranslation=[C(g*d),C(e*f)];a.transX=a.slicedTranslation[0];a.transY=a.slicedTranslation[1];a.slicedX=c?z(k)*d:0;a.slicedY=c?P(k)*f:0;b&&c&&a.graphic.attr({transform:"t"+
a.slicedTranslation[0]+","+a.slicedTranslation[1]})});this.placeDataLabels(!0,c)},plotMouseDown:function(){this.seriesData.isRotating=!1},plotMouseUp:function(){var a=this.chart,b=this.seriesData;!b.isRotating&&a.linkClickFN.call({link:b.data[this.index].link},a);ba._supportsTouch&&!b.isRotating&&a.plotGraphicClick.call(this)},plotDragStart:function(a,b,c){var d=this.seriesData,f=this.chart.datasets[0];if(f.enableRotation)a=La.call(c,a,b,d.pieCenter,d.chartPosition,f.pieYScale),f.dragStartAngle=a,
f._lastAngle=-f.startAngle},plotDragEnd:function(){var a=this.chart,b={hcJSON:{series:[{startAngle:a.datasets[0].startAngle}]}};a.disposed||ua(a.logic.chartInstance.jsVars._reflowData,b,!0)},plotDragMove:function(a,b,c,d,f){var g=this.chart,a=g.datasets[0],b=this.seriesData;if(g.options.series[0].enableRotation&&!b.singletonCase&&(b.isRotating=!0,c=La.call(f,c,d,b.pieCenter,b.chartPosition,a.pieYScale),d=c-a.dragStartAngle,a.dragStartAngle=c,b.moveDuration=0,a._lastAngle+=d*180/R,c=(new Date).getTime(),
!a._lastTime||a._lastTime+b.timerThreshold<c))a._lastTime||g.rotate(),b.timerId=setTimeout(function(){(!g.disposed||!g.disposing)&&g.rotate()},b.timerThreshold),a._lastTime=c},animate:function(a,b){var c,d,f,g=a.length,k,m,p,o=this,n;if(o.datasets[0].alphaAnimation)o.layers.dataset.attr({opacity:0}),o.layers.dataset.animate({opacity:1},b,"ease-in",function(){!o.disposed&&!o.disposing&&o.placeDataLabels(!1,a)});else for(c=0;c<g;c++)if(k=a[c],m=k.graphic,p=k.shapeArgs,k=2*R,m)m.attr({start:k,end:k}),
n=p.start,p=p.end,d?m.animateWith(d,f,{cx:n-k,cy:p-k},b,"ease-in"):(f=ba.animation({cx:n-k,cy:p-k},b,"ease-in",function(){!o.disposed&&!o.disposing&&o.placeDataLabels(!1,a)}),d=m.animate(f))},plotGraphicClick:function(){var a=this.seriesData,b=this.chart,c,d,f,g,k,m;if(!a.isRotating&&!a.singletonCase)return c=this.graphic,d=this.connector,f=this.dataLabel,a=this.sliced,g=this.connectorPath,k=(a?-1:1)*this.transX,m=(a?-1:1)*this.transY,c.animate({transform:a?"t0,0":"t"+k+","+m},200,"easeIn"),f&&f.x&&
f.animate({x:f.x+(a?0:k)},200,"easeIn"),g&&(g[1]+=k,g[2]+=m,g[4]+=k,g[6]+=k,d.animate({path:g},200,"easeIn")),a=this.sliced=!a,c={hcJSON:{series:[]}},c.hcJSON.series[0]={data:[]},ua(b.logic.chartInstance.jsVars._reflowData,c,!0),a},placeDataLabels:function(){var a=function(a,b){return a.point.value-b.point.value},b=function(a,b){return a.angle-b.angle},e=["start","start","end","end"],f=[-1,1,1,-1],m=[1,1,-1,-1];return function(p,k){var j=this.datasets[0],I=this.smartLabel,o=this.options.plotOptions.series.dataLabels,
n=o.style,r=i(Va(parseFloat(n.lineHeight)),12),l=Fa(o.placeInside,!1),y=o.skipOverlapLabels,R=o.manageLabelOverflow,u=o.connectorPadding,K=o.distance;Fa(o.softConnector,!0);var L=o.connectorWidth,q,v,K=K>0,E=j.center,M=E[1],N=E[0],F=E[2],s=E[4],x=[[],[],[],[]],D,Y,G,B=this.canvasLeft,H=this.canvasTop,S=this.canvasWidth,O,X,Z,Q,ca,ea,V,ja,da,ba,na,ha=j.labelsRadius,W=C(j.labelsRadiusY*100)/100,ka=j.labelFontSize,ga=ka,ma=ga/2,u=[u,u,-u,-u],Ba=j.maxLabels,Ia=j.isSmartLineSlanted,pa=j.enableSmartLabels,
oa,j=j.pieSliceDepth/2;p||I.setStyle(n);if(k.length==1){if(Q=k[0],oa=Q.dataLabel,Q.slicedTranslation=[B,H],oa)oa.attr({visibility:c,"text-anchor":"middle",x:N,y:M+ma-2}),oa.x=N}else if(l)va(k,function(a){if(oa=a.dataLabel){na=a.angle;ba=M+E[6]*P(na)+ma-2;V=N+E[5]*z(na);oa.x=V;oa._x=V;oa.y=ba;if(a.sliced){var a=a.slicedTranslation,b=a[1]-H;V+=a[0]-B;ba+=b}oa.attr({visibility:c,align:"middle",x:V,y:ba})}});else{va(k,function(a){if(oa=a.dataLabel)na=a.angle,na<0&&(na=ia+na),D=na>=0&&na<Ra?1:na<A?2:na<
wa?3:0,x[D].push({point:a,angle:na})});for(G=l=4;G--;){if(y&&(Q=x[G].length-Ba,Q>0)){x[G].sort(a);Y=x[G].splice(0,Q);X=0;for(Z=Y.length;X<Z;X+=1)Q=Y[X].point,Q.dataLabel.attr({visibility:"hidden"}),Q.connector&&Q.connector.attr({visibility:"hidden"})}x[G].sort(b)}G=fa(x[0].length,x[1].length,x[2].length,x[3].length);W=fa(w(G,Ba)*ga,W+ga);x[1].reverse();x[3].reverse();for(I.setStyle(n);l--;){X=x[l];Z=X.length;y||(ga=Z>Ba?W/Z:ka,ma=ga/2);Q=Z*ga;n=W;for(G=0;G<Z;G+=1,Q-=ga)v=la(W*P(X[G].angle)),n<v?v=
n:v<Q&&(v=Q),n=(X[G].oriY=v)-ga;Y=e[l];Z=W-(Z-1)*ga;n=0;for(G=X.length-1;G>=0;G-=1,Z+=ga){Q=X[G].point;na=X[G].angle;ca=Q.sliced;oa=Q.dataLabel;v=la(W*P(na));v<n?v=n:v>Z&&(v=Z);n=v+ga;ja=(v+X[G].oriY)/2;v=N+m[l]*ha*z(U.asin(ja/W));ja*=f[l];ja+=M;da=M+s*P(na);ea=N+F*z(na);(l<2&&v<ea||l>1&&v>ea)&&(v=ea);V=v+u[l];ba=ja+ma-2;q=V+u[l];oa.x=q;oa._x=q;R&&(O=l>1?q-this.canvasLeft:this.canvasLeft+S-q,O=I.getSmartText(Q.labelText,O,r),oa.attr({text:O.text,title:O.tooltext||""}));na<A&&(ja+=j,da+=j,ba+=j);oa.y=
ba;if(ca)ca=Q.transX,O=Q.transY,V+=ca,v+=ca,ea+=ca,da+=O,q+=ca;oa.attr({visibility:c,"text-anchor":Y,x:q,y:ja});if(K&&L&&pa)q=Q.connector,Q.connectorPath=v=[d,ea,da,g,Ia?v:ea,ja,V,ja],q?(q.attr({path:v}),q.attr("visibility",c)):Q.connector=q=this.paper.path(v).attr({"stroke-width":L,stroke:o.connectorColor||"#606060",visibility:c})}}}}}(),legendClick:function(a,b,c){a=b.elements.plots[0];a.isRotating=!1;b.plotGraphicClick.call(a.items[c])}},p["renderer.root"]);p("renderer.pie",{drawPlotPie:function(a,
b){var e=this,d=a.items,f=a.data,g=e.options,k=g.plotOptions,m=k.pie,p=k.series,o=e.layers,n=o.dataset,r=e.elements.plots[0],k=k.series.dataLabels,l=p.dataLabels.style,j=p.shadow,p=i(a.moveDuration,p.animation.duration),w=e.paper,g=(g=g.tooltip||{})&&g.enabled!==!1,u=(b.startAngle||0)%ia,A=m.slicedOffset,U=ia/b.valueTotal,q=e.canvasLeft+e.canvasWidth*0.5,v=e.canvasTop+e.canvasHeight*0.5,C=m.size*0.5,I=(m.innerSize||0)*0.5,y=e.plotGraphicClick,F=e.plotDragMove,s=e.plotDragStart,x=e.plotDragEnd,D=e.plotMouseDown,
K=e.plotMouseUp,R=!!e.datasets[0].enableRotation,B,H,L,O,fa,E,Q,la,G,N,Y,X=a.shadowGroup,Z,ea,ja;if(!f||!f.length)f=[];if(!X)X=a.shadowGroup=w.group(n).toBack();r.singletonCase=f.length==1;r.chartPosition||(r.chartPosition=Ca(e.container));r.pieCenter=[q,v];r.timerThreshold=30;N=G=u;for(Z=f.length;Z--;)if(H=f[Z],L=H.y,O=H.displayValue,E=H.sliced,m=H.toolText,Q=(fa=!!H.link)||R||!H.doNotSlice,!(L===null||L===void 0)){B=H.color.FCcolor;B.r=C;B.cx=q;B.cy=v;N=G;G-=!r.singletonCase?L*U:ia;la=(G+N)*0.5;
if(!(B=d[Z]))if(b.data[Z].plot=B=d[Z]={chart:e,index:Z,seriesData:r,value:L,angle:la,slicedX:z(la)*A,slicedY:P(la)*A,sliced:E,labelText:O,graphic:w.ringpath(q,v,C,I,u,u,o.dataset).attr({"stroke-width":H.borderWidth,stroke:H.borderColor,fill:V(H.color),"stroke-dasharray":H.dashStyle,redrawDataLabels:u,ishot:Q,cursor:fa?"pointer":""}).shadow(j&&H.shadow,X).drag(F,s,x).mousedown(D).mouseup(K)},H.doNotSlice||B.graphic.click(y),g&&B.graphic.tooltip(m),b.data[Z].legendClick=function(a){return function(){e.legendClick(null,
e,a)}}(Z),B.graphic.data("plotItem",B),O!==void 0&&(B.dataLabel=w.text(n).css(l).attr({text:O,fill:l.color||"#000000",ishot:Q}).click(y).drag(F,s,x).mousedown(D).mouseup(K).hide(),B.dataLabel.data("plotItem",B),k.distance>0&&(Y=k.connectorWidth)&&k.enableSmartLabels))B.connector=w.path("M 0 0 l 0 0",n).attr({"stroke-width":Y,stroke:k.connectorColor||"#606060",visibility:c,ishot:!0}).click(y).drag(F,s,x).mousedown(D).mouseup(K),B.connector.data("plotItem",B);B.angle=la;B.transX=z(la)*A;B.transY=P(la)*
A;B.slicedTranslation="t"+z(la)*A+","+P(la)*A;ea?B.graphic.animateWith(ea,ja,{ringpath:[q,v,C,I,G,N],transform:B.sliced?B.slicedTranslation:""},p,"easeIn"):(ja=ba.animation({ringpath:[q,v,C,I,G,N],redrawDataLabels:e,transform:B.sliced?B.slicedTranslation:""},p,"easeIn",function(){if(!e.disposed&&!e.disposing&&!e.paper.ca.redrawDataLabels)e.placeDataLabels(!1,d,a),e.paper.ca.redrawDataLabels=e.redrawDataLabels}),ea=B.graphic.animate(ja))}},rotate:function(a,b){var c=a.items,d=a.data,f=this.options.plotOptions.pie,
g=f.slicedOffset,m=ia/b.valueTotal,p=this.canvasLeft+this.canvasWidth*0.5,j=this.canvasTop+this.canvasHeight*0.5,o=f.size*0.5,f=(f.innerSize||0)*0.5,n,r,l,i,w;l=(b.startAngle||0)%ia;for(w=d.length;w--;)if(n=d[w],r=n.y,!(r===null||r===void 0))n=c[w],i=l,l-=!n.seriesData.singletonCase?r*m:ia,r=(l+i)*0.5,n.angle=r,n.transX=z(r)*g,n.transY=P(r)*g,n.slicedTranslation="t"+z(r)*g+","+P(r)*g,n.graphic.attr({ringpath:[p,j,o,f,l,i],transform:n.sliced?n.slicedTranslation:""});this.placeDataLabels(!0,c,a)}},
p["renderer.piebase"])},[3,2,2,"sr4"]]);
FusionCharts(["private","modules.renderer.js-zoomline",function(){var Ca=this,W=Ca.hcLib,sa=window,Da=/msie/i.test(navigator.userAgent)&&!sa.opera,La=W.chartAPI,Ea=W.chartAPI,ta=W.extend2,y=W.raiseEvent,ba=W.pluck,E=W.pluckNumber,N=W.getFirstColor,Ma=W.graphics.convertColor,j=W.defaultPaletteOptions,xa=W.bindSelectionEvent,i=W.createTrendLine,G=W.Raphael,Fa=W.FC_CONFIG_STRING,Pa="rgba(192,192,192,"+(Da?0.002:1.0E-6)+")",ka=Math,ha=ka.ceil,ua=ka.floor,Na=ka.max,V=ka.min,Ga=ka.cos,Ha=ka.sin,da=parseFloat,
za=parseInt,va=function(b){return b&&b.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")},pa;ta(W.eventList,{zoomed:"FC_Zoomed",pinned:"FC_Pinned",resetzoomchart:"FC_ResetZoomChart"});La("zoomline",{rendererId:"zoomline",standaloneInit:!0,hasVDivLine:!0,defaultSeriesType:"stepzoom",canvasborderthickness:1,defaultPlotShadow:1,chart:function(){var b=this.base.chart.apply(this,arguments),c=this.dataObj.chart,d=j.canvasBorderColor[this.paletteIndex],g=b.chart;ta(g,{animation:!1,zoomType:"x",canvasPadding:E(c.canvaspadding,
0),scrollColor:N(ba(c.scrollcolor,j.altHGridColor[g.paletteIndex])),scrollBtnWidth:E(c.scrollbtnwidth,c.scrollheight,16),scrollHeight:E(c.scrollheight,16)||16,allowPinMode:E(c.allowpinmode,1),skipOverlapPoints:E(c.skipoverlappoints,1),showToolBarButtonTooltext:E(c.showtoolbarbuttontooltext,1),btnResetChartTooltext:ba(c.btnresetcharttooltext,"Reset Chart"),btnZoomOutTooltext:ba(c.btnzoomouttooltext,"Zoom out one level"),btnSwitchToZoomModeTooltext:ba(c.btnswitchtozoommodetooltext,"<strong>Switch to Zoom Mode</strong><br/>Select a subset of data to zoom into it for detailed view"),
btnSwitchToPinModeTooltext:ba(c.btnswitchtopinmodetooltext,"<strong>Switch to Pin Mode</strong><br/>Select a subset of data and compare with the rest of the view"),pinPaneFill:Ma(ba(c.pinpanebgcolor,d),E(c.pinpanebgalpha,15)),zoomPaneFill:Ma(ba(c.zoompanebgcolor,"#b9d5f1"),E(c.zoompanebgalpha,30)),zoomPaneStroke:Ma(ba(c.zoompanebordercolor,"#3399ff"),E(c.zoompaneborderalpha,80))});return b},preSeriesAddition:function(){var b=this.dataObj,c=b.chart,d=(d=b.categories)&&d[0]||{},b=d.category,g=this.hcJSON,
f=g[Fa],m=this.smartLabel,j=E(c.compactdatamode,0),i=ba(c.dataseparator,"|"),z=E(c.showlabels,1),I=z&&E(c.labelheight),C=c.labeldisplay&&c.labeldisplay.toLowerCase()==="rotate"?270:E(c.rotatelabels,1)?270:0,w=g.xAxis.labels.style,y=da(w.lineHeight),la=g.chart.labelPadding=E(c.labelpadding,2)+g.chart.plotBorderWidth,R,G,N=0,K=-1,ea,A,V;delete d.category;g.categories=i=ta({data:R=j&&b&&b.split&&b.split(i)||b||[],rotate:C},d);b!==void 0&&(d.category=b);d=R.length||0;if(ea=!j&&z&&I!==0&&d||0){for(;ea--;)R[ea]=
R[ea]&&(G=R[ea].label||"")&&((A=G.length)>N&&(N=A,K=ea,G)||G)||"";N&&(G=R[K])}else if(j&&d)if(C){A=sa.document.createElement("div");I=sa.document.createElement("span");A.setAttribute("class","fusioncharts-zoomline-localsmartlabel");A.style.cssText="display:block;width:1px;position:absolute;";for(V in w)A.style[V]=w[V];I.appendChild(sa.document.createTextNode(b.replace(/\s*/g,"").replace(/\|/g," ")));A.appendChild(I);sa.document.body.appendChild(A);I=I.offsetWidth||void 0;A.parentNode.removeChild(A)}else G=
R[d-1]||R[0];I===void 0&&z&&(G?(m.setStyle(w),G=m.getSmartText(G),I=C?G.width:G.height):I=y*(C&&3||1));I>f.height*0.3&&(I=f.height*0.3);i.labelHeight=I&&I+10||0;i.show=I&&z||0;i.css=ta({},w);C?(i.css.rotation=C,i.css["text-anchor"]="end",C&&c.slantlabels==="1"&&(i.css.rotation+=45)):i.css["vertical-align"]="top";g.xAxis.min=0;g.xAxis.max=d&&d-1||0;I+=E(c.scrollheight,16)||16;g.chart.marginBottom+=la;f.marginBottomExtraSpace+=I;ba(c.caption,c.subcaption)||(f.marginTopExtraSpace+=16)},series:function(){var b=
this.dataObj,c=b.chart,d=b.dataset,g=this.hcJSON,f=g[Fa],m=f[0],j=g.series,P=E(c.yaxismaxvalue),z=E(c.yaxisminvalue),I=E(c.forceyaxislimits,0),C=E(c.compactdatamode,0),w=ba(c.dataseparator,"|"),y=va(c.indecimalseparator),G=va(c.inthousandseparator),R=E(c.drawanchors,c.showanchors,1),N=!!E(c.showlegend,1),Y,K,ea,A,W,ia=Infinity,wa=-Infinity,X;W=g.categories.data.length;if(d&&d.length&&W){y&&(y=RegExp(y,"g"));G&&(G=RegExp(G,"g"));!G&&!y&&C&&I&&P!==void 0&&z!==void 0?(I=!0,wa=Na(P,z),ia=V(z,P)):I=!1;
P=0;for(z=d.length;P<z;P++){Y=d[P];ea=Y.data;delete Y.data;C?(A=ea||"",G&&(A=A.replace(G,"")),y&&(A=A.replace(y,".")),A=A.split(w)):A=ea||[];if(A.length>W)A.length=W;X=A.length;if(C){if(!I)for(;X--;)K=da(A[X]),isNaN(K)&&(K=void 0),K>wa&&(wa=K),K<=ia&&(ia=K),A[X]=K}else for(;X--;)K=A[X]&&A[X].value||"",G&&(K=K.replace(G,"")),y&&(K=K.replace(y,".")),K=da(K),isNaN(K)&&(K=void 0),K>wa&&(wa=K),K<=ia&&(ia=K),A[X]=K;j.push(K={index:P,type:"zoomline",data:A,name:Y.seriesname||"",showInLegend:Y.seriesname&&
E(Y.includeinlegend,1)&&N||!1,showAnchors:E(Y.drawanchors,Y.showanchors,R),visible:!!E(Y.initiallyvisible,1),lineWidth:2});A.length=W;ea!==void 0&&(Y.data=ea);K.attrs=this.seriesGraphicsAttrs(Y,P);Y=K.attrs.anchors;K.color=K.attrs.graphics.stroke;K.ancorRadius=Y.r+Y["stroke-width"]/2;K.marker={fillColor:Y.fill,lineColor:Y.stroke,lineWidth:1,symbol:"circle"}}(wa===-Infinity||ia===Infinity)&&(wa=ia=void 0);I=za(E(c.displaystartindex,1),10)-1;w=za(E(c.displayendindex,W||2),10)-1;(d=E(c.pixelsperpoint,
15))<5&&(d=5);(j=E(c.pixelsperlabel,g.categories.rotate?20:60))<d&&(j=d);(I<0||I>=(W-1||1))&&(I=0);(w<=I||w>(W-1||1))&&(w=W-1||1);g.stepZoom={cnd:E(c.connectnulldata,0),amrd:E(c.anchorminrenderdistance,20),nvl:E(c.numvisiblelabels,0),cdm:C,oppp:d,oppl:j,dsi:I,dei:w,vdl:w-I,dmax:m.max=wa,dmin:m.min=ia,clen:W,offset:0,step:1,llen:0,alen:0,ddsi:I,ddei:w};g.crossline={style:{lineHeight:f.inCanvasStyle.lineHeight,fontSize:f.inCanvasStyle.fontSize,fontFamily:f.inCanvasStyle.fontFamily}};this.configureAxis(g,
b);b.trendlines&&i(b.trendlines,g.yAxis,f,!1,this.isBar)}},seriesGraphicsAttrs:function(b,c){var d=this.dataObj.chart,g=this.hcJSON.colors,f=(b.dashed||d.linedashed||"0")!=0,m,g={"stroke-width":E(b.linethickness,d.linethickness,2),stroke:N(ba(b.color,d.linecolor,g[c%g.length])),"stroke-opacity":E(b.alpha,d.linealpha,100)/100,"stroke-dasharray":f?[E(b.linedashlen,d.linedashlen,5),E(b.linedashgap,d.linedashgap,4)]:"none","stroke-linejoin":"round","stroke-linecap":"round"},f=ta({},g);m=g["stroke-width"]+
E(d.pinlinethicknessdelta,1);f["stroke-width"]=m>0&&m||0;f["stroke-dasharray"]=[3,2];return{graphics:g,pin:f,shadow:{opacity:g["stroke-opacity"],apply:E(d.showshadow,+!G.vml)},anchors:{"stroke-linejoin":"round","stroke-linecap":"round",r:E(b.anchorradius,d.anchorradius,g["stroke-width"]+2),stroke:N(ba(b.anchorbordercolor,d.anchorbordercolor,g.stroke)),"stroke-opacity":E(b.anchorborderalpha,d.anchorborderalpha,100)/100,"stroke-width":E(b.anchorborderthickness,d.anchorborderthickness,g["stroke-width"]),
fill:N(ba(b.anchorbgcolor,d.anchorbgcolor,"#ffffff")),"fill-opacity":E(b.anchorbgalpha,d.anchorbgalpha,100)/100,opacity:E(b.anchoralpha,d.anchoralpha,100)/100},anchorShadow:E(d.anchorshadow,d.showshadow,+!G.vml)&&{apply:!0,opacity:E(b.anchoralpha,d.anchoralpha,100)/100}}},eiMethods:{zoomOut:function(){var b=this.jsVars,c;if(b&&(c=b.hcObj))return c.zoomOut&&b.hcObj.zoomOut()},zoomTo:function(b,c){var d=this.jsVars,g;if(d&&(g=d.hcObj))return g.zoomRange&&d.hcObj.zoomRange(b,c-2)},resetChart:function(){var b=
this.jsVars,c;if(b&&(c=b.hcObj))c.pinRangePixels&&b.hcObj.pinRangePixels(),c.resetZoom&&b.hcObj.resetZoom()},setZoomMode:function(b){var c=this.jsVars,d;c&&(d=c.hcObj)&&b&&d.pinRangePixels&&c.hcObj.pinRangePixels()},getViewStartIndex:function(){var b=this.jsVars,c;if(b&&b.hcObj&&(c=b.hcObj._zoominfo))return c.ddsi+1},getViewEndIndex:function(){var b=this.jsVars,c;if(b&&b.hcObj&&(c=b.hcObj._zoominfo))return b=c.ddei-1,b>c.clen?c.clen:b}}},La.msline);Ea("renderer.zoomline",{resetZoom:function(){var b=
this._zoomhistory,c=this.options.stepZoom;if(!b.length)return!1;b.length=0;this.zoomTo(c.dsi,c.dei)&&y("resetzoomchart",this._zoomargs,this.fusionCharts,[this.fusionCharts.id]);return!0},zoomOut:function(){var b=this._zoomhistory.pop(),c=this.options.stepZoom,d,g,f;b?(d=b.dsi,g=b.dei):this._prezoomed&&(d=0,g=c.clen-1);(f=this.zoomTo(d,g))&&Ca.raiseEvent("zoomedout",f,this.fusionCharts);return!0},zoomRangePixels:function(b,c){var d=this._zoomhistory,g=this._zoominfo,f=g.ppp,g=g.ddsi,m;d.push(this._zoominfo);
(m=this.zoomTo(g+ua(b/f),g+ua(c/f)))?Ca.raiseEvent("zoomedin",m,this.fusionCharts):d.pop()},zoomRange:function(b,c){var d=this._zoomhistory,g;d.push(this._zoominfo);(g=this.zoomTo(+b-1,+c+1))?Ca.raiseEvent("zoomedin",g,this.fusionCharts):d.pop()},zoomTo:function(b,c){var d=this.xlabels.data,g=this._zoominfo,f=this._zoomhistory,m=g.clen;b<0&&(b=0);b>=m-1&&(b=m-1);c<=b&&(c=b+1);c>m-1&&(c=m-1);if(b===c||b===g.dsi&&c===g.dei)return!1;this.pinRangePixels();g=ta({},g);g.dsi=b;g.dei=c;g=this._zoominfo=g;
this.updatePlotZoomline();this.zoomOutButton[g.vdl===g.clen-1?"hide":"show"]();this.resetButton[f.length?"show":"hide"]();this.elements.zoomscroller.attr({"scroll-ratio":g.vdl/(m-!!m),"scroll-position":[g.dsi/(m-g.vdl-1),!0]});d={level:f.length+1,startIndex:b,startLabel:d[b],endIndex:c,endLabel:d[c]};y("zoomed",d,this.fusionCharts,[this.fusionCharts.id,b,c,d.startLabel,d.endLabel,d.level]);return d},activatePin:function(b){var c=this._zoominfo,d=this.options.chart,g=this.pinButton;if(g&&c.pinned^
(b=!!b))return b||this.pinRangePixels(),d.showToolBarButtonTooltext&&g.tooltip(d[b&&"btnSwitchToZoomModeTooltext"||"btnSwitchToPinModeTooltext"]||""),g.attr("button-active",b),c.pinned=b},pinRangePixels:function(b,c){var d=this.paper,g=this.elements,f=this.xlabels.data,m=this._zoominfo,j=this.layers.zoompin,i=g.pinrect,z=g["clip-pinrect"],I=this._pingrouptransform,C=this.plots,w=c-b,E,N;if(m&&j&&i){if(b===c)return j.hide(),g.pintracker.hide(),this.pinButton.attr("button-active",!1),m.pinned=!1;for(N=
C.length;N--;){i=C[N];E=i.pinline;if(!E)E=i.pinline=d.path(void 0,j).attr(i.attrPin);E.attr("path",i.graphic.attrs.path)}z[0]=b+(G.svg?this.canvasLeft:0);z[2]=w;j.attr({"clip-rect":z,transform:I}).show();g.pintracker.__pindragdelta=0;g.pintracker.show().attr({transform:I,x:b,width:w});b=this.getValuePixel(b);c=this.getValuePixel(c);y("pinned",{startIndex:b,endIndex:c,startLabel:f[b],endLabel:f[c]},this.fusionCharts,[this.fusionCharts.id,b,c,f[b],f[c]]);return m.pinned=!0}},getValuePixel:function(b){var c=
this._zoominfo;return c.ddsi+ua(b/c.ppp)},drawGraph:function(){var b=this,c=b.paper,d=b.canvasLeft,g=b.canvasTop,f=b.canvasWidth,m=b.canvasHeight,j=b.options,i=j.chart,z=i.plotBorderWidth,I=i.useRoundEdges,C=i.showToolBarButtonTooltext,w=b.layers,y=b.toolbar,E=b.elements,R=i.allowPinMode,N,Y=j.categories,K=!1,ea,A,W,V,ba,X;X=b._zoominfo=ta({},j.stepZoom);b._zoomhistory=[];if(X.clen){K=b._prezoomed=X.dei-X.dsi<X.clen-1;ba=b._visw=b.canvasWidth-i.canvasPadding*2;V=b._visx=b.canvasLeft+i.canvasPadding;
b._visout=-(b.chartHeight+b.canvasHeight+1E3);b.base.drawGraph.apply(b,arguments);b._ypvr=b.yAxis[0]&&b.yAxis[0].pixelValueRatio||0;N=b._yzero||0;j=w.dataset.attr("clip-rect",[b._visx,b.canvasTop,b._visw,b.canvasHeight]);W=w.scroll||(w.scroll=c.group("scroll").insertAfter(w.layerAboveDataset));b.xlabels=[];b.xlabels.show=Y.show;b.xlabels.rotate=Y.rotate;b.xlabels.data=Y.data||[];b.xlabels.css=Y.css;b.xlabels.group=c.group("zoomline-plot-xlabels",w.datalabels);w.datalabels.transform(["T",V,g+m+i.scrollHeight+
i.labelPadding]);b._lcmd=Y.rotate?"y":"x";if(R)R=G.crispBound(0,g-N,0,m,z),ea=E["clip-pinrect"]=[R.x,G.svg?g:R.y,R.width,R.height],A=w.zoompin=c.group("zoompin").insertBefore(j).transform(b._pingrouptransform=["T",V,N]).hide(),E.pinrect=c.rect(0,g-N,b._visw,m,w.zoompin).attr({"stroke-width":0,stroke:"none",fill:i.pinPaneFill,"shape-rendering":"crisp",ishot:!0}),E.pintracker=c.rect(w.tracker).attr({transform:A.transform(),x:0,y:g-N,width:0,height:m,stroke:"none",fill:Pa,ishot:!0,cursor:G.svg&&"ew-resize"||
"e-resize"}).drag(function(b){var c=V+b+this.__pindragdelta,d=this.__pinboundleft,f=this.__pinboundright;c<d?c=d:c>f&&(c=f);A.transform(["T",c,N]);E.pintracker.transform(A.transform());this.__pindragoffset=b},function(){this.__pinboundleft=0-ea[0]+V+(G.svg&&d||0);this.__pinboundright=this.__pinboundleft+ba-ea[2];A._.clipispath=!0},function(){A._.clipispath=!1;this.__pindragdelta=this.__pindragoffset;delete this.__pindragoffset;delete this.__pinboundleft;delete this.__pinboundright}),b.pinButton=y.add("pinModeIcon",
function(){b.activatePin(!b._zoominfo.pinned)},{tooltip:C&&i.btnSwitchToPinModeTooltext||""});z++;R=G.crispBound(d-z,g+m+z,f+z+z,i.scrollHeight,z);z--;E.zoomscroller=c.scroller(R.x+(I&&-1||z%2),R.y-(I&&4||2),R.width-(!I&&2||0),R.height,!0,{showButtons:!0,scrollRatio:X.vdl/(X.clen-!!X.clen),scrollPosition:[X.dsi/(X.clen-X.vdl-1),!1]},W).attr({fill:i.scrollColor,r:I&&2||0}).scroll(b.updatePlotZoomline,b);I&&E.zoomscroller.shadow(!0);xa(b,function(c){var f=c.selectionLeft-d,c=f+c.selectionWidth;b.crossline&&
b.crossline.hide();b[b._zoominfo.pinned?"pinRangePixels":"zoomRangePixels"](f,c)},{attr:{stroke:i.zoomPaneStroke,fill:i.zoomPaneFill,strokeWidth:0}});b.zoomOutButton=y.add("zoomOutIcon",function(){b.zoomOut()},{tooltip:C&&i.btnZoomOutTooltext||""})[K&&"show"||"hide"]();b.resetButton=y.add("resetIcon",function(){b.resetZoom()},{tooltip:C&&i.btnResetChartTooltext||""}).hide();R=b.resetButton.attr("fill");R[2]="rgba(255,255,255,0)";b.resetButton.attr("fill",[R[0],R[1],R[2],R[3]]);b.crossline=new pa(b);
b.updatePlotZoomline()}},drawPlotZoomline:function(b,c){var d=this.paper,g=this._yzero||(this._yzero=this.yAxis[0].getAxisPosition(0)),f=c.attrs,m=c.visible,j=m?"show":"hide",i=this.layers.dataset,z=b.group||(b.group=d.group("plot-zoomline-dataset",i)),i=b.anchorGroup||(b.anchorGroup=d.group("plot-zoomline-anchors",i)),d=b.graphic||(b.graphic=d.path(void 0,z)),g=["T",this._visx,g];z.transform(g)[j]();i.transform(g)[j]();b.graphic=d.attr(f.graphics).shadow(f.shadow);b.attrPin=f.pin;b.visible=m;b.anchors=
[];b.anchors.show=c.showAnchors;b.anchors.attrs=f.anchors;b.anchors.attrsShadow=f.anchorShadow;b.anchors.left=-(f.anchors.r+f.anchors["stroke-width"]*0.5);b.anchors.right=this._visw-b.anchors.right},updatePlotZoomline:function(b,c){var d=this.paper,g=this._ypvr,f=this._visw,m=this.xlabels,j=m.css,i=m.group,z=this.plots,I,C,w,y,E,G;!c&&(c=this._zoominfo);C=c.oppp;w=c.vdl=c.dei-c.dsi;c.ppl=c.oppl;y=c.ppl=c.nvl?f/c.nvl:c.oppl;f=c.step=(E=c.ppp=f/w)<C?ha(C/E):1;C=c.lskip=ha(y/E/f);b!==void 0?(y=(c.clen-
w-1)*b,c.offset=(y-(y=za(y)))*E,G=y+w):(y=c.dsi,G=c.dei,c.offset=0);w=c.norm=y%f;c.ddsi=y-=w;c.ddei=G=G+2*f-w;c.pvr=g;g=m.show?ha((G-y)/f/C):0;C=c.llen-1;c.llen=g;if(g>C){w=C;for(C=g;w<C;w++)(I=m[w])&&I.show()||(m[w]=d.text(0,0,"",i).css(j))}else{w=g;for(C+=1;w<C;w++)m[w].hide()}g=E*f<c.amrd?0:ha((G-y)/f);E=g-c.alen;c.alen=g;for(f=z.length;f--;){j=z[f];i=j.anchors;if(i.show&&E){I=i.attrs;w=0;for(C=g;w<C;w++)i[w]=i[w]&&i[w].show()||d.circle(0,0,0,j.anchorGroup).attr(I);w=g;for(C=i.length;w<C;w++)i[w]&&
i[w].hide()}this.drawPlotZoomlineGraphics(c,j.data,j.graphic,i,!f&&m)}if(window.FC_DEV_ENVIRONMENT)FusionCharts.debugMode.enabled()?(this.debug=this.debug||($("#fc-zoominfo").length||$("body").append('<pre id="fc-zoominfo">'),$("#fc-zoominfo").css({position:"absolute",left:"10px",top:"0","pointer-events":"none",opacity:0.7,width:"250px",zIndex:"999",border:"1px solid #cccccc","box-shadow":"1px 1px 3px #cccccc",background:"#ffffff"})),this.debug.text(JSON.stringify(c,0,2))):($("#fc-zoominfo").remove(),
delete this.debug)},drawPlotZoomlineGraphics:function(b,c,d,g,f){var m=[],i=!b.cnd,j=b.ddei,z=b.clen,y=b.step,C=b.lskip,w=b.ppp,E=b.offset,G=b.pvr,N=this._visw,V=this._visout,Y=this._lcmd,K="M",W,A,ba=f&&f[0],ia=ba&&f.data,g=g[0],da={},X={},Z,ja=0,ha,ka=-b.norm,b=b.ddsi,ga=0;for(ba&&f.group.transform(["T",-E,0]);b<=j;b+=y,ka+=y)if(ha=ja/3+ga,Z=ka*w,(W=c[b])===void 0?(i&&(K="M"),A=V,f=Z-E,W=V,ga++):(m[ja++]=K,m[ja++]=A=f=Z-E,m[ja++]=W*=G,K="L"),g&&(g=g.attr((da.cx=A,da.cy=W,da)).next),ba&&!(ha%C))ha=
ba.attrs,A=ia[b]||"",f=f<0||f>N?V:Z,ha.text===A?delete X.text:X.text=A,ha[Y]===f?delete X[Y]:X[Y]=f,ba=ba.attr(X).next;if(j>=z){if((W=c[z-1])!==void 0)ka-=j-z,m[ja++]="L",m[ja++]=ka*w-E,m[ja++]=W*G;g&&g.attr((da.cx=V,da.cy=V,da))}d.attr("path",m)},legendClick:function(b){var c=!b.visible,d=c?"show":"hide";b.group[d]();b.anchorGroup[d]();this.base.legendClick.apply(this,arguments);return b.visible=c}},Ea["renderer.cartesian"]);pa=function(b){var c=b.paper,d=this.left=b._visx,g=this.width=b._visw,f=
b.canvasTop,m=b.canvasHeight,i=b._visout,j=this.plots=b.plots,z=b.layers.dataset,y=this.group=c.group("crossline-labels",z).attr({transform:["T",d,b._yzero]});this.tracker=c.rect(d,f,g,m,z).attr({stroke:"none","stroke-width":0,fill:Pa}).toFront().mousedown(this.onMouseDown,this).mouseup(this.onMouseUp,this,!0).mouseout(this.onMouseOut,this).mousemove(this.onMouseMove,this);this.line=c.path(void 0,z).attr({path:["M",d,f,"l",0,m],"stroke-opacity":0.2}).toBack();d=this.labels=c.set();g=b.options.crossline.style;
this.hide();this.pixelRatio=b._ypvr;this.getZoomInfo=function(){return b._zoominfo};this.getDataIndexFromPixel=function(c){return b.getValuePixel(c)};f=0;for(m=j.length;f<m;f++)z=j[f],z=z.graphic.attrs.stroke,d.push(c.text(0,i,"",y).css(g).attr({fill:z,"text-bound":["rgba(255,255,255,0.8)","rgba(0,0,0,0.2)",1,2]}))};pa.prototype.onMouseOut=function(){this.hide()};pa.prototype.onMouseDown=function(){this.hide();this._mouseIsDown=!0};pa.prototype.onMouseUp=function(){this.hide();delete this._mouseIsDown};
pa.prototype.onMouseMove=function(b){if(!this._mouseIsDown){var c=this.getZoomInfo(),d=this.line,g=c.step,f=c.ppp*g,b=(b.layerX||b.x)-this.left,m,b=(b+=f/2+c.offset)-b%f;m=(m=this.getDataIndexFromPixel(b))+m%g;b-=c.offset;d.transform(["T",ua(b),0]);if(m!==this.position||this.hidden)this.position=m,this.lineX=b,this.updateLabels();this.hidden&&this.show()}};pa.prototype.updateLabels=function(){var b=this.plots,c=this.width,d=this.position,g=this.lineX,f=this.pixelRatio,m;this.labels.forEach(function(i,
j){m=b[j].data[d];i.attr({text:m+"",x:ua(g),y:m===void 0?-1E3:m*f,"text-anchor":g<=0&&"start"||g>=c&&"end"||"middle"})})};pa.prototype.show=function(){this.hidden=!1;this.group.show();this.line.show()};pa.prototype.hide=function(){this.hidden=!0;this.group.hide();this.line.hide()};G.addSymbol({pinModeIcon:function(b,c,d){var g=d*0.5,f=b-d,m=b+d,i=b-g,j=b+g,z=b+0.5,y=z+1,C=z+1.5,w=c-d,E=c+g,G=c-g,g=c+(d-g);return["M",f,w,"L",i,G,i,g,f,E,b-0.5,E,b,c+d+0.5,z,E,m,E,j,g,j,G,m,w,C,w,C,G,C,g,y,g,y,G,C,G,
C,w,"Z"]},zoomOutIcon:function(b,c,d){b-=d*0.2;c-=d*0.2;var g=d*0.8,f=G.rad(43),i=G.rad(48),j=b+g*Ga(f),f=c+g*Ha(f),y=b+g*Ga(i),i=c+g*Ha(i),z=G.rad(45),E=j+d*Ga(z),C=f+d*Ha(z),w=y+d*Ga(z),d=i+d*Ha(z);return["M",j,f,"A",g,g,0,1,0,y,i,"Z","M",j+1,f+1,"L",E,C,w,d,y+1,i+1,"Z","M",b-2,c,"L",b+2,c,"Z"]},resetIcon:function(b,c,d){var g=b-d,f=(ka.PI/2+ka.PI)/2;b+=d*Ga(f);var f=c+d*Ha(f),i=d*2/3;return["M",g,c,"A",d,d,0,1,1,b,f,"L",b+i,f-1,b+2,f+i-0.5,b,f]}})}]);