/*
 FusionCharts JavaScript Library - Gantt Chart
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version fusioncharts/3.3.1-sr1.19666
*/
FusionCharts(["private","modules.renderer.js-gantt",function(){var I=this.hcLib,pa=window,Z=/msie/i.test(navigator.userAgent)&&!pa.opera,Ba=pa=I.chartAPI,La=I.extend2,e=I.pluck,c=I.pluckNumber,Y=I.getFirstColor,ma=I.graphics,T=ma.convertColor,Ca=ma.getDarkColor,Wa=ma.parseColor,Da=I.parseUnsafeString,Ma=I.getFirstValue,ga=I.Raphael,Xa=I.COMMASTRING,qa=I.setLineHeight,Na=I.getDashStyle,Oa=I.toRaphaelColor,ra=I.each,Ya=I.FC_CONFIG_STRING,na="rgba(192,192,192,"+(Z?0.002:1.0E-6)+")",Za=ma.mapSymbolName,
Z=Math,ea=Z.ceil,aa=Z.round,U=Z.max,fa=Z.min,sa=parseInt,Pa=parseFloat,$a={pageX:0,pageY:0},K,N,Ua=I.hasTouch=document.documentElement.ontouchstart!==void 0,ab=I.addEvent,bb=I.removeEvent,Ea=function(a){return a!==void 0&&a!==null},Qa={left:"start",right:"end",center:"middle"},Ra={left:0,right:1,center:0.5,undefined:0.5},Va={top:1,bottom:0,middle:0.5,undefined:0.5},Sa={left:5,right:-5,center:0,undefined:0},Z=!/fusioncharts\.com$/i.test(location.hostname),ha=function(a,b){this.min=a.min;this.max=c(a.visibleMax,
a.max);this.pixelValueRatio=b/(this.max-this.min);this.startPixel=a.chart.marginLeft+a.chart.ganttStartX};ha.prototype={getPixel:function(a){return this.startPixel+(a-this.min)*this.pixelValueRatio}};ha.prototype.constructor=ha;pa("gantt",{rendererId:"gantt",standaloneInit:!0,defaultSeriesType:"gantt",canvasborderthickness:1,defaultPlotShadow:1,creditLabel:Z,defaultGaugePaletteOptions:function(){var a=arguments;return jQuery.extend(!0,null,a[0],a[1],a[2],a[3])}(I.defaultGaugePaletteOptions,{paletteColors:[["AFD8F8",
"F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D",
"A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600","663300","6DCFF6"],["AFD8F8","F6BD0F","8BBA00","FF8E46","008E8E","D64646","8E468E","588526","B3AA00","008ED6","9D080D","A186BE","CC6600","FDC689","ABA000","F26D7D","FFF200","0054A6","F7941C","CC3300","006600",
"663300","6DCFF6"]],bgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],bgAngle:[270,270,270,270,270],bgRatio:["100","100","100","100","100"],bgAlpha:["100","100","100","100","100"],canvasBgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],canvasBgAngle:[0,0,0,0,0],canvasBgAlpha:["100","100","100","100","100"],canvasBgRatio:["","","","",""],canvasBorderColor:["545454","545454","415D6F","845001","68001B"],canvasBorderAlpha:[100,100,100,90,100],gridColor:["DDDDDD","D8DCC5","99C4CD","DEC49C","FEC1D0"],
gridResizeBarColor:["999999","545454","415D6F","845001","D55979"],categoryBgColor:["F1F1F1","EEF0E6","F2F8F9","F7F0E6","FFF4F8"],dataTableBgColor:["F1F1F1","EEF0E6","F2F8F9","F7F0E6","FFF4F8"],toolTipBgColor:["FFFFFF","FFFFFF","FFFFFF","FFFFFF","FFFFFF"],toolTipBorderColor:["545454","545454","415D6F","845001","68001B"],baseFontColor:["555555","60634E","025B6A","A15E01","68001B"],borderColor:["767575","545454","415D6F","845001","68001B"],borderAlpha:[50,50,50,50,50],legendBgColor:["ffffff","ffffff",
"ffffff","ffffff","ffffff"],legendBorderColor:["666666","545454","415D6F","845001","D55979"],plotBorderColor:["999999","8A8A8A","6BA9B6","C1934D","FC819F"],plotFillColor:["EEEEEE","D8DCC5","BCD8DE","E9D8BE","FEDAE3"],scrollBarColor:["EEEEEE","D8DCC5","99C4CD","DEC49C","FEC1D0"]}),charttopmargin:10,chartbottommargin:20,series:function(){var a=this.dataObj,b=a.chart,M=(M=a.categories)||[],d=M.length,v=this.hcJSON,h=v.chart,x=v[Ya],m=this.smartLabel,f=this.colorM,i=v.categories={},B=[],p=this.inCanvasStyle,
t=this.numberFormatter,o=Infinity,j=-Infinity,g=h.origW-h.marginLeft-h.marginRight,y=h.origH-h.marginTop-h.marginBottom,l=a.processes||{},k=l&&l.process,q=k&&k.length,r=sa(p.fontSize,10),G=a.datatable,L=G&&G.datacolumn,C=L&&L.length,H=a.connectors,O=H&&H.length,ba=v.connectors=[],Q=a.milestones&&a.milestones.milestone,z=Q&&Q.length,n=v.milestone=[],u=a.tasks,Ta=u&&u.task,w=Ta&&Ta.length,I=0;v.tasks=[];var ia=0,A=c(b.forceganttwidthpercent,0),P=0,E=0,R=!1,K={top:"top",bottom:"bottom"},N={top:"top",
bottom:"bottom",undefined:"middle"},Z={right:"right",left:"left"},ta={right:"right",left:"left",undefined:"center"},J=v.dataTable={},Fa=Infinity,Ga=-Infinity,ea=v.processIDMap=[],ca={},pa=c(b.dateintooltip,1),ma=a.legend&&a.legend.item,ga,ha,Ha,F,$,s,D,ua,va,wa,Ia,xa,ya,ja,ka,Ba,ra,V,X,Ja,Ka,za,S,la,da,W,Aa;if(q){delete v.yAxis;delete v.xAxis;h.backgroundColor=T(e(b.bgcolor,"FFFFFF"),e(b.bgalpha,f.get2DBgAlpha()));if(!c(b.showborder,0))h.borderWidth=0;h.plotBorderColor=T(e(b.canvasbordercolor,f.get2DCanvasBorderColor()),
c(b.showcanvasborder,1)===0?0:e(b.canvasborderalpha,100));h.backgroundColor={FCcolor:{color:e(b.bgcolor,"FFFFFF"),alpha:e(b.bgalpha,f.get2DBgAlpha()),angle:e(b.bgangle,f.get2DBgAngle()),ratio:e(b.bgratio,f.get2DBgRatio())}};h.plotBackgroundColor={FCcolor:{color:e(b.canvasbgcolor,f.get2DCanvasBgColor()),alpha:e(b.canvasbgalpha,f.get2DCanvasBgAlpha()),angle:e(b.canvasbgangle,f.get2DCanvasBgAngle()),ratio:e(b.canvasbgratio,f.get2DCanvasBgRatio())}};h.plotBorderWidth=c(b.canvasborderthickness,1);h.outputDateFormat=
e(b.outputdateformat,h.dateFormat);h.extendCategoryBg=c(b.extendcategorybg,0);h.ganttLineColor=T(e(b.ganttlinecolor,f.getGridColor()),c(b.ganttlinealpha,100));h.ganttLineThickness=c(b.ganttlinethickness,1);h.ganttLineDashStyle=c(b.ganttlinedashed,0)?Na(c(b.ganttlinedashlen,1),b.ganttlinedashgap,h.ganttLineThickness):void 0;h.gridBorderColor=T(e(b.gridbordercolor,f.getGridColor()),c(b.gridborderalpha,100));h.gridBorderThickness=c(b.gridborderthickness,1);h.gridBorderDashStyle=c(b.gridborderdashed,
0)?Na(c(b.gridborderdashlen,1),b.gridborderdashgap,h.gridborderThickness):void 0;h.showSlackAsFill=c(b.showslackasfill,1);h.slackFillColor=Y(e(b.slackfillcolor,"FF5E5E"));h.gridResizeBarColor=T(e(b.gridresizebarcolor,f.getGridResizeBarColor()),c(b.gridresizebaralpha,100));h.gridResizeBarThickness=c(b.gridresizebarthickness,1);h.taskBarRoundRadius=c(b.taskbarroundradius,0);h.taskBarFillMix=b.taskbarfillmix;h.taskBarFillRatio=b.taskbarfillratio;if(h.taskBarFillMix===void 0)h.taskBarFillMix="{light-10},{dark-20},{light-50},{light-85}";
if(h.taskBarFillRatio===void 0)h.taskBarFillRatio="0,8,84,8";h.connectorExtension=c(b.connectorextension,10);h.clickURL=e(b.clickurl,"");h.annRenderDelay=b.annrenderdelay;h.taskDatePadding=c(b.taskdatepadding,3);h.ganttStartX=c(b.ganttwidthpercent,65);if(h.ganttStartX>100)h.ganttStartX=100;o=h.ganttStartX=(100-h.ganttStartX)*0.01*g;h.gridWidth=g-h.ganttStartX;j=c(b.showfulldatatable,1);g=l.width;g=c(h.ganttStartX*(/\%/g.test(g)&&Pa(g,10)*0.01)||g);o-=c(g,0);ca.width=aa(g);E+=1;for(g=0;g<C;g+=1)F=
L[g].width,F=c(h.ganttStartX*(/\%/g.test(F)&&Pa(F,10)*0.01)||F),o-=c(F,0),L[g].width=aa(F),E+=1;o>=0?o/=E:(R=!0,o=h.ganttStartX/E);if(A||!j){(isNaN(ca.width)||R)&&(ca.width=o);for(g=0;g<C;g+=1)(isNaN(L[g].width)||R)&&(L[g].width=o)}for(g=0;g<d;g+=1){X=M[g];o=Infinity;j=-Infinity;Ja=e(X.bgcolor,f.getCategoryBgColor());Ka=c(X.bgalpha,100);ua=e(X.font,p.fontFamily);va=c(X.fontsize,r+1);wa=e(X.fontcolor,p.color);Ia=c(X.isbold,1);xa=c(X.isitalic,0);ya=c(X.isunderline,0);c(X.verticalpadding,3);ja=e(X.align,
"center").toLowerCase();ka=e(X.valign,"middle").toLowerCase();Ba=(ra=X.category)&&ra.length;la=0;W={};for(S=0;S<Ba;S+=1){V=ra[S];F=t.getDateValue(V.start).ms;D=t.getDateValue(V.end).ms;isNaN(F)&&(F=void 0);F>j&&(j=F);F<=o&&(o=F);isNaN(D)&&(D=void 0);D>j&&(j=D);D<=o&&(o=D);R=Da(e(V.label,V.name));E={color:Y(e(V.fontcolor,wa)),fontFamily:e(V.font,ua),fontSize:c(V.fontsize,va)+"px",fontWeight:c(V.isbold,Ia)&&"bold"||"normal",fontStyle:c(V.isitalic,xa)&&"italic"||"normal",textDecoration:c(V.isunderline,
ya)&&"underline"||"none"};qa(E);m.setStyle(E);$=m.getOriSize(R);la=U(la,$.height);s="FCCAT_"+g+"_"+S;ga=e(V.hoverbandcolor,X.hoverbandcolor,b.categoryhoverbandcolor,b.hoverbandcolor,f.getGridColor());ha=c(V.hoverbandalpha,X.hoverbandalpha,b.categoryhoverbandalpha,b.hoverbandalpha,30);Ha=c(V.showhoverband,X.showhoverband,b.showcategoryhoverband,b.showhoverband,b.showhovereffect,1);i[s]={text:R,style:E,start:F,end:D,index:S,isLast:g===d-1,bgColor:T(e(V.bgcolor,Ja),c(V.bgalpha,Ka)),dimension:W,link:V.link,
align:ta[[e(V.align,ja).toLowerCase()]],vAlign:N[K[e(V.valign,ka).toLowerCase()]],hoverColor:T(ga,ha),useHover:Ha,usePlotHover:c(V.showganttpanehoverband,X.showganttpanehoverband,b.showganttpaneverticalhoverband,Ha)};if(i[da])i[da].nextCol=i[s],i[s].prevCol=i[da];da=s}if(E=i["FCCAT_"+g+"_0"])if(i[s].first=E,E.last=i[s],i[za])i[za].nextRow=E,E.prevRow=i[za];za=s;W.h=la+5+c(X.verticalpadding,3)*2;W.y=ia;W.min=o;W.max=j;W.numCat=S;ia+=W.h;Ga=U(Ga,j);Fa=fa(Fa,o)}i.min=Fa;i.max=Ga;if(q){la=o=0;Aa=e(l.positioningrid,
"left").toLowerCase()==="right";E={color:Y(e(l.headerfontcolor,p.color)),fontFamily:e(l.headerfont,p.fontFamily),fontSize:c(l.headerfontsize,r+3)+"px",fontWeight:c(l.headerisbold,1)&&"bold"||"normal",fontStyle:c(l.headerisitalic,0)&&"italic"||"normal",textDecoration:c(l.headerisunderline,0)&&"underline"||"none"};qa(E);R=Da(l.headertext);m.setStyle(E);$=m.getOriSize(R);o=U(o,$.width);ja=ta[Z[e(l.headeralign,"center").toLowerCase()]];ka=N[K[e(l.headervalign,"middle").toLowerCase()]];W={};s=j=za="processHeader";
J.processHeader={text:R,style:E,align:ja,vAlign:ka,isHeader:!0,dimension:{x:0,w:0,h:U($.height,ia)},bgColor:T(e(l.headerbgcolor,f.getDataTableBgColor()),c(l.headerbgalpha,100)),key:s,isLast:Aa,drawResizer:!Aa&&C,prevCol:null,nextCol:null,prevRow:null,nextRow:null};Ja=e(l.bgcolor,f.getDataTableBgColor());Ka=c(l.bgalpha,100);ua=e(l.font,p.fontFamily);va=c(l.fontsize,r);wa=e(l.fontcolor,p.color);Ia=c(l.isbold,0);xa=c(l.isitalic,0);ya=c(l.isunderline,0);ja=e(l.align,"center").toLowerCase();ka=e(l.valign,
"middle").toLowerCase();for(g=0;g<q;g+=1)F=k[g],ga=e(F.hoverbandcolor,l.hoverbandcolor,b.processhoverbandcolor,b.hoverbandcolor,f.getGridColor()),ha=c(F.hoverbandalpha,l.hoverbandalpha,b.processhoverbandalpha,b.hoverbandalpha,30),Ha=c(F.showhoverband,l.showhoverband,b.showprocesshoverband,b.showhoverband,b.showhovereffect,1),E={color:Y(e(F.fontcolor,wa)),fontSize:c(F.fontsize,va)+"px",fontFamily:e(F.font,ua),fontWeight:c(F.isbold,Ia)&&"bold"||"normal",fontStyle:c(F.isitalic,xa)&&"italic"||"normal",
textDecoration:c(F.isunderline,ya)&&"underline"||"none"},qa(E),R=Da(e(F.label,F.name)),m.setStyle(E),$=m.getOriSize(R),la=U(la,$.height),o=U(o,$.width),da=s,s=e(F.id,"__FCDPID__"+g).toUpperCase(),J[s]&&(s="__FCDPID__"+g),ea[g]=s,J[s]={text:$.text,style:E,link:F.link,id:s,align:ta[[e(F.align,ja).toLowerCase()]],vAlign:N[K[e(F.valign,ka).toLowerCase()]],bgColor:T(e(F.bgcolor,Ja),c(F.bgalpha,Ka)),prevCol:J[da],dimension:W,hoverColor:T(ga,ha),useHover:Ha,usePlotHover:c(F.showganttpanehoverband,l.showganttpanehoverband,
b.showganttpanehorizontalhoverband,Ha),isLast:Aa,nextCol:null,prevRow:null,nextRow:null},J[da]&&(J[da].nextCol=J[s]);J[s].first=J[j];J[j].last=J[s];J[j].processCount=q;J[j].maxProcessHeight=la+8;ca.height=la+8;isNaN(ca.width)&&(ca.width=o+10);P+=ca.width;W.x=0;J[j].dimension.w=W.w=ca.width;W.h=ca.height=U((y-J[j].dimension.h)/q,ca.height)}Aa&&(P=0);if(C){v.datacolumns=[];for(g=0;g<C;g+=1){D=L[g];o=0;Ja=Y(e(D.bgcolor,G.bgcolor,f.getDataTableBgColor()));Ka=c(D.bgalpha,G.bgalpha,100);ua=e(D.font,G.font,
p.fontFamily);wa=Y(e(D.fontcolor,G.fontcolor,p.color));va=c(D.fontsize,G.fontsize,r);Ia=c(D.isbold,G.isbold,0);xa=c(D.isitalic,G.isitalic,0);ya=c(D.isunderline,G.isunderline,0);ja=ta[Z[e(D.align,G.align,"center").toLowerCase()]];ka=N[K[e(D.valign,G.valign,"middle").toLowerCase()]];E={color:Y(e(D.headerfontcolor,G.headerfontcolor,wa)),fontFamily:e(D.headerfont,G.headerfont,ua),fontSize:c(D.headerfontsize,G.headerfontsize,va+3)+"px",fontWeight:c(D.headerisbold,G.headerisbold,1)&&"bold"||"normal",fontStyle:c(D.headerisitalic,
G.headerisitalic,xa)&&"italic"||"normal",textDecoration:c(D.headerisunderline,G.headerisunderline,ya)&&"underline"||"none"};qa(E);R=Da(D.headertext);m.setStyle(E);$=m.getOriSize(R);o=U(o,$.width);s=j="_FCDtHeader_"+g;F=J[s]={text:R,style:E,align:ta[Z[e(D.headeralign,G.headeralign,ja).toLowerCase()]],vAlign:N[K[e(D.headervalign,G.headervalign,ka).toLowerCase()]],link:e(D.headerlink),drawResizer:Aa||g<C-1,dimension:{x:0+P,w:D.width,h:J.processHeader&&J.processHeader.dimension.h},isHeader:!0,key:s,bgColor:T(e(D.headerbgcolor,
G.headerbgcolor,f.getDataTableBgColor()),c(D.headerbgalpha,G.headerbgalpha,100))};F.data=[];l=D.text||[];ia=J.processHeader;y=J[za];y.nextRow=J[s];J[s].prevRow=y;ia=ia.nextCol;y=y.nextCol;W={};za=j;for(S=0;ia;ia=ia.nextCol,y=y.nextCol,S+=1)da=s,s="_FCDt_"+g+"_"+S,(k=l[S])?(E={fontFamily:e(k.font,ua),color:Y(e(k.fontcolor,wa)),fontSize:c(k.fontsize,va)+"px",fontWeight:c(k.isbold,Ia)&&"bold"||"normal",fontStyle:c(k.isitalic,xa)&&"italic"||"normal",textDecoration:c(k.isunderline,ya)&&"underline"||"none"},
qa(E),m.setStyle(E),R=Da(k.label),$=m.getOriSize(R),o=U(o,$.width),J[s]={text:R,style:E,link:e(k.link,""),bgColor:T(e(k.bgcolor,Ja),c(k.bgalpha,Ka)),align:ta[Z[e(k.align,ja).toLowerCase()]],vAlign:N[K[e(k.valign,ka).toLowerCase()]],prevCol:J[da],dimension:W,nextCol:null,nextRow:null,prevRow:null}):J[s]={prevCol:J[da],dimension:W,isNaN:!0,nextCol:null,nextRow:null,prevRow:null},J[da].nextCol=J[s],J[s].prevRow=y,y.nextRow=J[s],J[s].hoverColor=J[ea[S]].hoverColor,J[s].useHover=J[ea[S]].useHover,J[s].usePlotHover=
J[ea[S]].usePlotHover;J[s].first=J[j];J[j].last=J[s];F.width=isNaN(D.width)?o+10:D.width;W.x=0+P;P+=J[j].dimension.w=W.w=F.width;W.h=ca.height;v.datacolumns.push(F)}}if(Aa)F=J.processHeader,F.dimension.x=F.nextCol.dimension.x=P,P+=ca.width;if(!A)h.ganttStartX=fa(h.ganttStartX,P);h.totalGridWidth=P;for(g=0;g<O;g+=1)if(E=(s=(D=H[g])&&D.connector)&&s.length)for(S=0;S<E;S+=1)m=s[S],R=e(m.color,D.color,f.get2DPlotBorderColor()),o=c(m.alpha,D.alpha,100),j=c(m.thickness,D.thickness,1),F=c(m.isdashed,D.isdashed,
1),ba.push({fromTaskId:Ma(m.fromtaskid,"").toUpperCase(),toTaskId:Ma(m.totaskid,"").toUpperCase(),fromTaskConnectStart:c(m.fromtaskconnectstart,0),toTaskConnectStart:c(m.totaskconnectstart,1),color:T(R),alpha:o*0.01,link:m.link,showHoverEffect:c(m.showhovereffect,D.showhovereffect,b.showconnectorhovereffect,b.showhovereffect,1),hoverColor:T(e(m.hovercolor,D.hovercolor,b.connectorhovercolor,Ca(R,80)),c(m.hoveralpha,D.hoveralpha,b.connectorhoveralpha,o)),hoverThickness:c(m.hoverthickness,D.hoverthickness,
b.connectorhoverthickness,j),thickness:j,dashedStyle:F?Na(c(m.dashlen,D.dashlen,5),c(m.dashgap,D.dashgap,j),j):void 0});for(g=0;g<z;g+=1)s=Q[g],R=Ma(s.taskid,"").toUpperCase(),H=e(s.shape,"polygon").toLowerCase(),E=c(s.numsides,5),O=0,H==="star"?O=0.4:(H=Za(E),H.split("-")),H=e(s.color,f.get2DLegendBorderColor()),n.push({numSides:E,startAngle:c(s.startangle,90),radius:s.radius,date:t.getDateValue(s.date),fillColor:Y(H),fillAlpha:c(s.fillalpha,s.alpha,100)*0.01,borderColor:Y(e(s.bordercolor,H)),borderAlpha:c(s.borderalpha,
s.alpha,100)*0.01,hoverFillColor:Y(e(s.hoverfillcolor,b.milestonehoverfillcolor,Ca(H,80))),hoverFillAlpha:c(s.hoverfillalpha,b.milestonehoverfillalpha,s.fillalpha,s.alpha,100)*0.01,hoverBorderColor:Y(e(s.hoverbordercolor,b.milestonehoverbordercolor,Ca(e(s.bordercolor,H),80))),hoverBorderAlpha:c(s.hoverborderalpha,b.milestonehoverborderalpha,s.borderalpha,s.alpha,100)*0.01,showHoverEffect:c(s.showhovereffect,b.showmilestonehovereffect,b.showhovereffect,0),depth:O,taskId:R,borderThickness:c(s.borderthickness,
1),link:s.link,toolText:e(s.tooltext,s.hovertext)});s=a.trendlines||{};v.trendlines=[];for(g=0;g<s.length;g+=1){z=(a=s[g].line)&&a.length;for(S=0;S<z;S+=1)n=a[S],Q=c(n.istrendzone,0),H=e(n.color,f.get2DLegendBorderColor()),E=La({},x.trendStyle),E.color=T(H),qa(E),v.trendlines.push({start:t.getDateValue(n.start).ms,end:t.getDateValue(n.end).ms,displayValue:e(n.displayvalue,n.start),color:T(H,c(n.alpha,Q?40:99)),style:E,isTrendZone:Q,dashedStyle:c(n.dashed,0)?Na(c(n.dashlen,3),c(n.dashgap,3),c(n.thickness,
1)):void 0,thickness:c(n.thickness,1)})}if(w){o=Infinity;j=-Infinity;c(b.taskbarroundradius,0);z=b.taskbarfillmix;x=b.taskbarfillratio;z===void 0&&(z="{light-10},{dark-20},{light-50},{light-85}");x===void 0&&(x="0,8,84,8");h.shadow=c(b.showshadow,1);h=c(b.showslackasfill,1);for(g=0;g<w;g+=1)a=Ta[g],s=I%q,F=t.getDateValue(a.start).ms,D=t.getDateValue(a.end).ms,s=e(J[a.processid],J["__FCDPID__"+s],J[ea[s]]).id.toUpperCase(),Q=c(a.alpha,u.alpha,100),H=e(a.color,u.color,f.get2DPlotFillColor()),O=c(a.borderalpha,
u.borderalpha,100),n=e(a.bordercolor,u.bordercolor,f.get2DPlotBorderColor()),isNaN(F)&&(F=void 0),F>j&&(j=F),F<=o&&(o=F),isNaN(D)&&(D=void 0),D>j&&(j=D),D<=o&&(o=D),E={color:Y(e(a.fontcolor,u.fontcolor,p.color)),fontSize:c(a.fontsize,u.fontsize,r)+"px",fontFamily:e(a.font,u.font,p.fontFamily)},qa(E),I+=1,C=f.parseColorMix(H,z),L=f.parseAlphaList(Q.toString(),C.length),A=f.parseRatioList(x,C.length),P=c(a.angle,u.angle,270),S=f.parseColorMix(e(a.slackfillcolor,u.slackfillcolor,b.slackfillcolor,"FF5E5E"),
z),m=fa(c(a.percentcomplete,-1),100),R=Ma(e(a.label,a.name),""),ba="",c(a.showlabel,a.showname,u.showlabels,u.showname,b.showtasklabels,b.showtasknames,0)&&(ba=R),c(a.showpercentlabel,u.showpercentlabel,b.showpercentlabel,0)&&m!==-1&&(ba+=" "+m+"%"),G={FCcolor:{color:C.join(),alpha:L,ratio:A,angle:P}},S=h?{FCcolor:{color:S.join(),alpha:L,ratio:A,angle:P}}:na,H={FCcolor:{color:f.parseColorMix(e(a.hoverfillcolor,u.hoverfillcolor,b.taskhoverfillcolor,Ca(H,80)),z).join(),alpha:f.parseAlphaList(e(a.hoverfillalpha,
u.hoverfillalpha,b.taskhoverfillalpha,Q).toString(),C.length),ratio:A,angle:P}},L=T(e(a.hoverbordercolor,u.hoverbordercolor,b.taskhoverbordercolor,Ca(n,80)),e(a.hoverborderalpha,u.hoverborderalpha,b.taskhoverborderalpha,O)),P=h?{FCcolor:{color:f.parseColorMix(Ca(e(a.slackhoverfillcolor,u.slackhoverfillcolor,b.slackhoverfillcolor,b.slackfillcolor,"FF5E5E"),80),z).join(),alpha:f.parseAlphaList(e(a.slackhoverfillalpha,u.slackhoverfillalpha,b.slackhoverfillalpha,Q).toString(),C.length),ratio:A,angle:P}}:
na,C=t.getFormatedDate(F),A=t.getFormatedDate(D),B.push({processId:s,label:ba,labelAlign:ta[[e(a.labelalign,"center").toLowerCase()]],link:a.link,start:F,end:D,id:Ma(a.id,"").toUpperCase(),showAsGroup:c(a.showasgroup,0),animation:c(a.animation,b.animation,b.defaultanimation,1),style:E,percentComplete:m,color:Oa(G),slackColor:Oa(S),hoverFillColor:Oa(H),hoverBorderColor:L,slackHoverColor:Oa(P),showHoverEffect:c(a.showhovereffect,u.showhovereffect,b.showtaskhovereffect,b.showhovereffect,1),shadow:{opacity:U(Q,
O)/100,inverted:!0},borderColor:T(n,O),borderThickness:c(a.showborder,u.showborder,1)?c(a.borderthickness,u.borderthickness,1):0,height:e(a.height,"35%"),topPadding:e(a.toppadding,"35%"),showPercentLabel:c(a.showpercentlabel,u.showpercentlabel,b.showpercentlabel,0),startDate:c(a.showstartdate,u.showstartdate,b.showtaskstartdate)&&C,endDate:c(a.showenddate,u.showenddate,b.showtaskenddate)&&A,toolText:e(a.tooltext,a.hovertext,(R!==""?R+(pa?", ":""):"")+(pa?C+" - "+A:"")),_start:a.start,_end:a.end});
Ga=U(Ga,j);Fa=fa(Fa,o)}v.series.push({showInLegend:!1,data:B});v.legend.enabled=Boolean(c(b.showlegend,1));v.legend.interactiveLegend=!1;v.legend.itemStyle.cursor="default";v.legend.itemHoverStyle={cursor:"inherit"};z=ma&&ma.length;for(g=0;g<z;g+=1)b=ma[g],Ea(b.label)&&b.label!==""&&v.series.push({name:Da(b.label),showInLegend:!0,type:!1,color:Wa(e(b.color,f.getColor()))});v.max=Ga;v.min=Fa;v.chart.hasScroll=!0;return v}},spaceManager:function(a,b,M,d){I.titleSpaceManager(a,b,M,d*0.3);var v=this.numberFormatter,
h=a.chart,x=b.chart,m=a.dataTable,f=a.categories,i=a.scrollOptions={},B=m.__scrollOptions={},m=m.processHeader,d=d-h.marginTop-h.marginBottom,M=M-h.marginLeft-h.marginRight,p=h.totalGridWidth,t=a.verticalScroll={enabled:c(x.useverticalscrolling,1)},o=c(x.ganttpaneduration,-1),j=e(x.ganttpanedurationunit,"s").toLowerCase(),v=v.getDateValue(x.scrolltodate).ms,g=m&&m.maxProcessHeight;if(m){a.legend.enabled&&(d-=I.placeLegendBlockBottom(a,b,M,d/2));d-=m.dimension.h;i.padding=c(x.scrollpadding,a.chart.plotBorderWidth/
2);i.height=c(x.scrollheight,16);i.buttonWidth=c(x.scrollbtnwidth,i.height);i.buttonPadding=c(x.scrollbtnpadding,0);i.flatScrollBars=c(x.flatscrollbars,0);i.color=Y(e(x.scrollcolor,this.colorM.get2DAltHGridColor()));b=i.height+i.padding;if(p>h.ganttStartX)B.enabled=!0,B.startPercent=Boolean(c(x.scrolltoend,0));M-=h.ganttStartX;f.scroll={};i=new Date(f&&f.min);if(o!==-1){switch(j){case "y":i.setYear(i.getFullYear()+o);break;case "m":i.setMonth(i.getMonth()+o);break;case "d":i.setDate(i.getDate()+o);
break;case "h":i.setHours(i.getHours()+o);break;case "mn":i.setMinutes(i.getMinutes()+o);break;default:i.setSeconds(i.getSeconds()+o)}i=i.getTime();if(i>a.min&&i<a.max)a.visibleMax=i,f.scroll.enabled=!0}if(B.enabled||f.scroll.enabled)d-=b;B=d/m.processCount;g=c(x.rowheight,g);g-B>0&&(g-B<3?g=B:g=d/aa(d/g));m.maxProcessHeight=g;t.enabled&&B<g?(B=g,t.startPercent=Boolean(c(x.scrolltoend,0)),M-=b):t.enabled=!1;f.scroll.startPercent=c(x.scrolltoend,0);if(a.min===Infinity||a.max===-Infinity||a.min===a.max)a.min=
f.min=0,a.max=f.max=1;if(f.min===Infinity||f.max===-Infinity)f.min=a.min,f.max=a.max;f.axis=new ha(a,M);f.startX=f.axis.getPixel(fa(f.min,a.min));f.endX=f.axis.getPixel(U(f.max,a.max));f.visibleW=M;if(v&&v>f.min&&v<f.max)f.scroll.startPercent=fa((f.axis.getPixel(v)-f.startX)/(f.endX-f.startX-f.visibleW),1);for(h.processHeight=d+m.dimension.h;m;)m.nextCol&&(m.nextCol.dimension.h=B),m=m.nextRow}}},pa.gaugebase);Ba("renderer.gantt",{drawProcess:function(a){var b=this,c=b.options,d=c.chart,v=b.paper,
h=b.logic,x=h.smartLabel,m=b.canvasTop,f=b.canvasLeft,i=b.layers,B=i.gridLayer,p=i.gridHeaderLayer,t=d.gridBorderThickness,o=t*0.5,j=d.gridBorderColor,g=d.gridBorderDashStyle;fa(d.ganttStartX,d.totalGridWidth);var y=0,l=0,k=[],q=m,r=a.dimension.w||16,G=a.dimension.x||0,L=c.dataTable.processHeader,C=L.nextCol.dimension.h,H=L.dimension.h+L.processCount*L.nextCol.dimension.h,h=T(e(h.dataObj.chart.rolloverbandcolor,"#FF0000"),e(h.dataObj.chart.rolloverbandalpha,30)),O=L.items||(L.items={}),ba=c.categories||
{},c=function(){var a=this.data("link");this.data("dataObj");a&&b.linkClickFN.call({link:a},b)},Q,z,n,u,I,w,oa;if(!O.hoverEle)O.hoverEle=v.rect(ba.startX,0,ba.endX,C,i.dataset).attr({fill:h,visibility:"hidden","stroke-width":0});for(;a;){oa=a.dimension;w=f+G;z=a.text;z=a.align;O=a.items||(a.items={});C=a.link;Q=a.isHeader?p:B;n=O.background;ba=ea(q+l)-0.5;z={x:ea(w+y)-0.5,y:ba,width:r+0.5,height:oa.h+o+0.5,fill:a.bgColor||na,"stroke-dasharray":g,stroke:j,cursor:C?"pointer":"","stroke-width":0};n?
n.attr(z):(O.background=v.rect(Q).attr(z).hover(function(){K=clearTimeout(K);N&&b.gridOutHandler.call(N);N=null;b.gridHoverHandler.call(this)},function(){N=this;K=clearTimeout(K);K=setTimeout(function(){b.gridOutHandler.call(N)},500)}),O.background.click(c).data("link",C).data("dataObj",a).data("data",{y:ba,gridObj:a,rollOverColor:h,useHover:!0,useNext:!0,hoverEle:L.items.hoverEle}));if(!a.isNaN&&(oa=a.dimension,z=a.text,z=a.align,n=O.label,z=a.text,Ea(z)&&z!==""))I=a.style,x.setStyle(I),u=x.getSmartText(z,
r-8,U(sa(I.lineHeight,10),oa.h)),I.title=u.oriText,z=a.align,z={text:u.text,x:w+r*Ra[z]+Sa[z],y:q+oa.h-oa.h*Va[a.vAlign],"text-anchor":Qa[z],cursor:C?"pointer":"","vertical-align":a.vAlign},n?n.attr(z):O.label=v.text(Q).attr(z).css(I).hover(function(){K=clearTimeout(K);N&&b.gridOutHandler.call(N);N=null;b.gridHoverHandler.call(this)},function(){N=this;K=clearTimeout(K);K=setTimeout(function(){b.gridOutHandler.call(N)},500)}).click(c).data("link",C).data("dataObj",a).data("data",{y:ba,gridObj:a,rollOverColor:h,
useHover:!0,useNext:!0,hoverEle:L.items.hoverEle});a.xPos=w;a.yPos=ea(q+oa.h)-t%2*0.5;k.push("M",w,a.yPos,"h",r);(n=O.hBorder)?n.attr("path",k):O.hBorder=v.path(k,Q).attr({"stroke-dasharray":g,stroke:j,"stroke-width":t});q+=oa.h;if(!a.nextCol&&(y=o,l-=0,n=a.first.items.vBorder,z=["M",ea(w+r)-t%2*0.5,m,"v",H],n?n.attr("path",z):a.first.items.vBorder=v.path(z,p).attr({"stroke-dasharray":g,stroke:j,"stroke-width":t}),a.nextRow&&!a.isLast)){if(!a.first.items.dragEle)a.first.items.dragEle=v.path(z,i.gridTracker).attr({stroke:d.gridResizeBarColor,
"stroke-width":d.gridResizeBarThickness,visibility:"hidden"});if(!a.first.items.tracker)a.first.items.tracker=v.path(z,i.gridTracker).attr({stroke:na,ishot:!0,"stroke-width":30}).css("cursor",ga.svg&&"ew-resize"||"e-resize").drag(this.dragMove,this.dragStart,this.dragUp).data("drag-options",{grid:a.first,xPos:ea(w+r)-t%2*0.5,chart:b})}a=a.nextCol}},dragStart:function(){var a=this.data("drag-options"),b=a.grid,M=b.items,d=b.nextRow,e={style:{lineHeight:16}},h=b.nextCol.style||e,x=d&&d.nextCol&&d.nextCol.style||
e,m=a.chart,f=m.canvasLeft,i=b.dimension,h=U(sa(b.style.lineHeight,10),sa(h.lineHeight,10))+2,e=U(sa((d||e).style.lineHeight,10),sa(x.lineHeight,10))+2;a.leftSideLimit=f+c(b.dimension.x,0)+h;a.rightSideLimit=f+c(d&&d.dimension.x+d.dimension.w,i.x+i.w)-e;a.origX=a.lastX||(a.lastX=0);M.dragEle.show();m.trackerClicked=!0;a.draged=!1},dragMove:function(a){var b=this.data("drag-options"),c=b.grid.items,d=b.xPos+a,e=b.leftSideLimit,h=b.rightSideLimit;d<e&&(a=e-b.xPos);d>h&&(a=h-b.xPos);d={transform:"t"+
(b.origX+a)+Xa+0};this.attr(d);c.dragEle.attr(d);b.draged=!0;b.lastX=a},dragUp:function(){var a=this.data("drag-options"),b=a.chart,c=a.grid,d=c.nextRow,e=b.canvasLeft,h=c.dimension,x=d&&d.dimension,m=c.items,f={hcJSON:{dataTable:{}}};b.trackerClicked=!1;m.dragEle.hide();if(a.draged){h.w=a.xPos+a.lastX-e-h.x;c.nextCol&&(c.nextCol.dimension.w=h.w);f.hcJSON.dataTable[c.key]={dimension:h};if(d)x.w+=x.x-h.x-h.w,x.x=h.x+h.w,d.dimension.w=x.w,d.dimension.x=x.x,b.drawProcess(d),f.hcJSON.dataTable[d.key]=
{dimension:x};b.drawProcess(c);La(b.logic.chartInstance.jsVars._reflowData,f,!0);a.xPos+=a.lastX;a.lastX+=a.origX}},drawCategories:function(){var a=this,b=a.options,e=b.chart,d=a.paper,v=a.layers,h=a.logic.smartLabel,x=a.canvasTop,m=b.categories,f=b.dataTable.processHeader,i=m.FCCAT_0_0,B=m.axis,p=m.endX,t=m.startX,o=p-t,j=e.ganttLineThickness,g=f.totalPH+f.dimension.h,y=[],l=[],k=v.dataset,v=v.ganttHeaderLayer,q=function(){var b=this.data("link");b&&a.linkClickFN.call({link:b},a)},r,G,L,C,H,O,I,
Q,z,n,u;L=m.items||(m.items={});f=b.dataTable.processHeader;for(L.hoverEle=d.rect(0,x+f.dimension.h,50,g,k).attr({fill:na,visibility:"hidden","stroke-width":0});i;)r=o/i.dimension.numCat,C=t+r*(i.index+1),Q=C-r,I=i.dimension.h,z=Q,u=x+i.dimension.y,H=i.align,O=i.vAlign,G=i.link,L=i.items||(i.items={}),r=!(!i.nextRow&&i.nextCol),n=b.verticalScroll.enabled&&r?b.scrollOptions.height:0,Q=z=c(B.getPixel(i.start),Q),C=c(B.getPixel(!r&&i.nextCol.start||(r?U(i.end||0,b.max):void 0)),C),r=C-Q,z=aa(z)+0.5,
u=aa(u)+0.5,i.isLast&&(y.push("M",z,u,"v",g),u-=j*0.5,I-=j,e.extendCategoryBg&&d.rect(z,u,r,g,k).attr({fill:i.bgColor,"stroke-width":0,stroke:e.ganttLineColor}).toBack()),L.background=d.rect(z,u,r+n,I,v).attr({fill:i.bgColor,"stroke-width":0,cursor:G?"pointer":"",stroke:e.ganttLineColor}).click(q).data("link",G).data("dataObj",i).hover(function(){K=clearTimeout(K);N&&a.gridOutHandler.call(N);N=null;a.gridHoverHandler.call(this)},function(){N=this;K=clearTimeout(K);K=setTimeout(function(){a.gridOutHandler.call(N)},
500)}).data("data",{x:z,width:r,gridObj:i,hoverEle:m.items.hoverEle}),l.push("M",z,u,"v",I),i.nextRow&&l.push("M",t,u+I,"H",p+n),h.setStyle(i.style),C=h.getSmartText(i.text,r-5,I),i.style.title=C.oriText,L.label=d.text(v).attr({text:C.text,x:z+r*Ra[H]+Sa[H],y:u+I-I*Va[O],"text-anchor":Qa[H],cursor:G?"pointer":"","vertical-align":O}).css(i.style).hover(function(){K=clearTimeout(K);N&&a.gridOutHandler.call(N);N=null;a.gridHoverHandler.call(this)},function(){N=this;K=clearTimeout(K);K=setTimeout(function(){a.gridOutHandler.call(N)},
500)}).click(q).data("link",G).data("dataObj",i).data("data",{x:z,width:r,gridObj:i,hoverEle:m.items.hoverEle}),i=i.nextCol;for(;f;)y.push("M",m.startX,f.yPos,"H",p),f=f.nextCol;L=m.items||(m.items={});L.headerGrid=d.path(l,v).attr({"stroke-dasharray":e.ganttLineDashStyle,"stroke-width":j,stroke:e.ganttLineColor});L.processGrid=d.path(y,k).attr({"stroke-dasharray":e.ganttLineDashStyle,"stroke-width":e.ganttLineThickness,stroke:e.ganttLineColor})},drawScroller:function(){var a=this.options,b=this.paper,
e=this.layers,d=this.canvasTop,v=this.canvasHeight,h=a.scrollOptions,x=a.categories,m=x.startX,f=x.endX-m,i=h.flatScrollBars,B={hcJSON:{categories:{scroll:{}}}},p=e.dataset,t=e.datalabels,o=e.ganttTracker,j=e.ganttHeaderLayer,g=this.logic.chartInstance&&this.logic.chartInstance.jsVars._reflowData||{},y=a.chart,l=e.gridLayer,k=(m=a.dataTable)&&m.processHeader,q=this.canvasLeft,r=this.canvasWidth,G=y.gridBorderThickness,L=y.totalGridWidth,C=fa(y.ganttStartX,L)+G,G=x.scroll,H=m&&m.__scrollOptions,a=
a.verticalScroll,O={hcJSON:{dataTable:{__scrollOptions:{}},verticalScroll:{}}},I=O.hcJSON.dataTable.__scrollOptions,m=c(x.startX,y.ganttStartX),Q=k.totalPH=k.processCount*k.nextCol.dimension.h,z=e.gridHeaderLayer,n=e.gridTracker,u,K,w,N;if(G.enabled)N=e.scroll=e.scroll||b.group("scroll").insertAfter(o),K=x.visibleW/f,G.scroller=b.scroller(m,d+v-h.height,x.visibleW,h.height,!0,{showButtons:!0,displayStyleFlat:i,buttonWidth:h.buttonWidth,scrollRatio:K,scrollPosition:G.startPercent},N).attr({"scroll-display-style":i,
fill:h.color}).scroll(function(a){w=-aa(a*(f-x.visibleW));p&&p.transform(["T",w,p.data("vOffset")]);t&&t.transform(["T",w,t.data("vOffset")]);o&&o.transform(["T",w,o.data("vOffset")]);j&&j.transform(["T",w,0]);p&&p.data("hOffset",w);t&&t.data("hOffset",w);o&&o.data("hOffset",w);B.hcJSON.categories.scroll.startPercent=a;La(g,B,!0)}),G.startPercent&&(w=-aa(G.startPercent*(f-x.visibleW)),p&&p.data("hOffset",w),t&&t.data("hOffset",w),o&&o.data("hOffset",w),j&&j.transform(["T",w,0]),p&&p.transform(["T",
w,p.data("vOffset")]),t&&t.transform(["T",w,p.data("vOffset")]),o&&o.transform(["T",w,p.data("vOffset")]));if(H.enabled)N=e.scroll=e.scroll||b.group("scroll").insertAfter(o),H.scroller=b.scroller(q,d+v-h.height,C,h.height,!0,{showButtons:!0,displayStyleFlat:i,buttonWidth:h.buttonWidth,scrollRatio:C/L,scrollPosition:H.startPercent},N).attr({"scroll-display-style":i,fill:h.color}).scroll(function(a){w=-aa(a*(L-C));l&&l.transform(["T",w,l.data("vOffset")]);z&&z.transform(["T",w,0]);n&&n.transform(["T",
w,n.data("vOffset")]);l.data("hOffset",w);z.data("hOffset",w);n.data("hOffset",w);I.startPercent=a;La(g,O,!0)}),H.startPercent&&(w=-aa(H.startPercent*(L-C)),l&&l.transform(["T",w,0]),n&&n.transform(["T",w,0]),z&&z.transform(["T",w,0]),l.data("hOffset",w),n.data("hOffset",w));if(a.enabled)u=y.processHeight-k.dimension.h,a.scroller=b.scroller(q+r-h.height,d+k.dimension.h,h.height,y.processHeight-k.dimension.h,!1,{showButtons:!0,displayStyleFlat:i,buttonWidth:h.buttonWidth,scrollRatio:u/Q,scrollPosition:a.startPercent},
N).attr({"scroll-display-style":i,fill:h.color}).scroll(function(a){w=-aa(a*(Q-u));l&&l.transform(["T",l.data("hOffset"),w]);p&&p.transform(["T",p.data("hOffset"),w]);t&&t.transform(["T",t.data("hOffset"),w]);o&&o.transform(["T",o.data("hOffset"),w]);n&&n.transform(["T",n.data("hOffset"),w]);l.data("vOffset",w);n.data("vOffset",w);p.data("vOffset",w);o.data("vOffset",w);t.data("vOffset",w);O.hcJSON.verticalScroll.startPercent=a;La(g,O,!0)}),a.startPercent&&(w=-aa(a.startPercent*(Q-u)),l&&l.transform(["T",
l.data("hOffset"),w]),p&&p.transform(["T",p.data("hOffset"),w]),t&&t.transform(["T",t.data("hOffset"),w]),o&&o.transform(["T",o.data("hOffset"),w]),n&&n.transform(["T",n.data("hOffset"),w]),l.data("vOffset",w),n.data("vOffset",w),p.data("vOffset",w),t.data("vOffset",w),o.data("vOffset",w))},finalizeScrollPlots:function(){var a=this,b=a.options,c=a.canvasTop,d=b.categories,e=d.endX,h=d.startX,x=d.scroll,m=b.chart,f=b.dataTable,i=f&&f.processHeader,B=a.canvasLeft,p=m.gridBorderThickness,t=m.totalGridWidth,
o=fa(m.ganttStartX,t)+p,j={},g=e-h-d.visibleW,e=a.container,x=d.scroll,y=f&&f.__scrollOptions,l=b.verticalScroll,k=i.totalPH,q=m.processHeight-i.dimension.h,r,G,L,C,H,b=function(b){var e=a.elements.canvas,f=C.left,m=C.top,n=b.type,p=Ua&&I.getTouchEvent(b)||$a,f=b.layerX||p.layerX||(b.pageX||p.pageX)-f,b=b.layerY||p.layerY||(b.pageY||p.pageY)-m;switch(n){case "dragstart":H=e.isPointInside(f,b);r=f>h&&f<h+d.visibleW;L=f>B&&f<h+d.visibleW&&b>c+i.dimension.h;G=f<h;j.ox=H&&f||null;j.oy=H&&b||null;break;
case "dragend":H=!1;j={};break;default:if(!H||a.trackerClicked)break;e=f-j.ox;n=b-j.oy;j.ox=f;j.oy=b;if(r&&x&&x.scroller)j.scrollPosition=x.scroller.attrs["scroll-position"]-e/g,x.scroller.attr({"scroll-position":j.scrollPosition});if(L&&l&&l.scroller)j.vScrollPosition=l.scroller.attrs["scroll-position"]-n/(k-q),l.scroller.attr({"scroll-position":j.vScrollPosition});if(G&&y&&y.scroller)j.pScrollPosition=y.scroller.attrs["scroll-position"]-e/(t-o),y.scroller.attr({"scroll-position":j.pScrollPosition})}};
Ua&&(C=I.getPosition(e),e&&(bb(e,"dragstart drag dragend",b),ab(e,"dragstart drag dragend",b)))},gridHoverHandler:function(){var a=this.data("data"),b=a.gridObj,c=!!b.prevRow,d={};if(!b.isHeader)if(a.x&&(d.x=a.x),a.y&&(d.y=a.y),a.width&&(d.width=a.width),a.height&&(d.height=a.height),b.hoverColor&&(d.fill=b.hoverColor),b.usePlotHover&&a.hoverEle.attr(d).show(),a.useNext&&b.useHover){for(;b&&c;)b=b.prevRow,c=!!b.prevRow;for(;b;)b.items.background.attr("fill",b.hoverColor),b=b.nextRow}else b.useHover&&
b.items.background.attr("fill",b.hoverColor)},gridOutHandler:function(){var a=this.data("data"),b=a.gridObj,c=!!b.prevRow;if(!b.isHeader)if(b.usePlotHover&&a.hoverEle.hide(),a.useNext&&b.useHover){for(;b&&c;)b=b.prevRow,c=!!b.prevRow;for(;b;)b.items.background.attr("fill",b.bgColor||na),b=b.nextRow}else b.useHover&&b.items.background.attr("fill",b.bgColor)},drawAxes:function(){var g;if(this.options.dataTable){Ba["renderer.cartesian"].drawAxes.call(this,arguments);var a=this.options,b=a.chart,e=this.paper,
d=this.layers,v=d.layerBelowDataset,h=d.layerAboveDataset,x=d.gridLayer,m=d.dataset,f=a.dataTable,i=a.categories,f=f&&f.processHeader,B=this.canvasTop,m=this.canvasLeft,x=b.gridBorderThickness,p=fa(b.ganttStartX,b.totalGridWidth)+x,t=f.dimension,o=t.h,t=b.processHeight-t.h,j=c(i.startX,b.ganttStartX),i=i.visibleW,b=b.ganttLineThickness*0.5;x*=0.5;f.totalPH=f.processCount*f.nextCol.dimension.h;x=d.gridLayer=d.gridLayer||e.group("grid",v).attr({"clip-rect":[m,B+o+x,p,t-x]});d.gridHeaderLayer=d.gridHeaderLayer||
e.group("grid-header",v).attr({"clip-rect":[m,B,p,o+t]});v=d.gridTracker=d.gridTracker||e.group("grid-tracker",v).attr({"clip-rect":[m,B,p,o+t]});x.data("vOffset",0);x.data("hOffset",0);v.data("vOffset",0);v.data("hOffset",0);d.ganttHeaderLayer=d.ganttHeaderLayer||e.group("gantt",h).attr({"clip-rect":[j,B,i+(a.verticalScroll.enabled?a.scrollOptions.height:0),this.chartHeight]});m=d.dataset.attr({"clip-rect":[j,B+o-b,i,t+b]});a=d.datalabels.attr({"clip-rect":[j,B+o-b-10,i,t+b+10]});g=d.ganttTracker=
e.group("gantt-hot",d.tracker).attr({"clip-rect":[j,B+o-b,i,t+b]}),e=g;m.data("vOffset",0);m.data("hOffset",0);a.data("vOffset",0);a.data("hOffset",0);e.data("vOffset",0);for(e.data("hOffset",0);f;)this.drawProcess(f),f=f.nextRow;this.drawCategories()}},drawPlotGantt:function(a){var b=this,M=b.options,d=M.chart,v=b.paper,h=b.layers,x=a.data,m=a.items;a.graphics=[];var f=x.length,a=h.dataset,i=h.datalabels,B=M.dataTable,p=B.processHeader,t=M.categories,o=t.axis,j=b.canvasTop,g=d.taskBarRoundRadius,
f=M.plotOptions.series,y=isNaN(+f.animation)&&f.animation.duration||f.animation*1E3,l=M.tasksMap||(M.tasksMap={}),k=M.milestone,q=M.trendlines,r=p.dimension.h,G=function(){var a=this.data("link"),c=this.data("dataObj");a&&b.linkClickFN.call({link:a},b);a={processId:c.processId,taskId:c.id,start:c._start,end:c._end,showAsGroup:c.showAsGroup,percentComplete:c.percentComplete!==-1&&c.percentComplete};I.raiseEvent("taskclicked",a,b.logic.chartInstance,[b.logic.chartInstance.id,a.processId,a.taskId,a.start,
a.end,a.showAsGroup,a.percentComplete])},L=d.taskDatePadding,C,H,O,N,Q,z,n,u,K,w,T,U,A,P,E;U=a.shadows||(a.shadows=v.group("shadows",a));f=q&&q.length;for(M=0;M<f;M+=1)if(n=q[M],n.end||(n.end=n.start),n.end&&(P=o.getPixel(n.start),z=o.getPixel(n.end),E=n.thickness,u=n.items||(n.items={}),C=void 0,n.isTrendZone?(Q=["M",P+(z-P)*0.5,j+r,"v",j+p.totalPH],E=z-P):(Q=["M",P,j+r,"L",z,j+r+p.totalPH],C=n.dashedStyle),u.trendLine=v.path(Q,a).attr({stroke:n.color,"stroke-width":E,"stroke-dasharray":C}),Ea(n.displayValue)&&
n.displayValue!==""))u.label=v.text(h.ganttHeaderLayer).attr({text:n.displayValue,x:Q[1],y:0}).css(n.style),C=u.label._getBBox().height,n=j+d.processHeight+(!t.scroll.enabled||d.marginBottom<C?C*0.5:-(C*0.5)-5),u.label.attr("y",n);i.hide();f=x.length;for(M=0;M<f;M+=1)if(A=x[M],u=A.processId,n=B[u],p=t=A.color,u=A.items||(A.items={}),h=A.animation?y||1E3:0,n&&(j=A.borderThickness,P=aa(o.getPixel(A.start)),E=O=o.getPixel(A.end)-P,P&&E)){q=n.dimension.h;n=n.yPos-q;C=q*(/%/g.test(A.height)&&Pa(A.height,
10)*0.01)||c(A.height,q);r=q*(/%/g.test(A.topPadding)&&Pa(A.topPadding,10)*0.01)||c(A.topPadding,q);n+=fa(r,q-C);T=C*0.5;w=A.toolText;K=A.link;if(!(q=m[M]))q=m[M]={index:M,dataLabel:null,start:A.start,end:A.end,startLabel:null,endLabel:null,tracker:null};A.index=M;r=e(A.id,M);r!==""&&!l[r]&&(l[r]={dataObj:A,items:q,x:P,y:n,h:C,w:E});H=r=O=N=Q=z=null;if(A.showAsGroup)H=v.path(["M",P,n],a),H.animate({path:["M",P,n,"v",C,"L",P+T,n+T,"H",P+E-T,"L",P+E,n+C,"v",-C,"H",P]},h,"normal",function(){i.show()}).attr({fill:p,
stroke:A.borderColor,cursor:K?"pointer":"",ishot:!0,"stroke-width":A.borderThickness}).tooltip(w).shadow(d.shadow&&A.shadow,U);else{if(A.percentComplete!==-1)O=E*A.percentComplete*0.01,p=na,r=u.taskFill=v.rect(P,n,0,C,a).attr({fill:t,cursor:K?"pointer":"",ishot:!0,"stroke-width":0}).animate({width:O||1},h,"normal").tooltip(w),O=v.rect(P,n,0,C,a).attr({fill:A.slackColor,cursor:K?"pointer":"",ishot:!0,"stroke-width":0}).animate({x:P+O||1,width:E-O||1},h,"normal").tooltip(w);u=ga.crispBound(P,n,E,C,
j);H=v.rect(u.x,u.y,0,u.height,g,a).attr({fill:p,stroke:A.borderColor,cursor:K?"pointer":"",ishot:!0,"stroke-width":A.borderThickness}).animate({width:u.width||1},h,"normal",function(){i.show()}).tooltip(w).shadow(d.shadow&&A.shadow,U)}if(Ea(A.label)&&A.label!=="")u=A.labelAlign,N=v.text().attr({text:A.label,x:P+E*Ra[u]+Sa[u],"text-anchor":Qa[u],cursor:K?"pointer":"",ishot:!0,y:n-sa(A.style.lineHeight,10)*0.5-5}).css(A.style),i.appendChild(N);Ea(A.startDate)&&A.startDate!==""&&(Q=v.text().attr({text:A.startDate,
x:P-2-L,y:n+C*0.5,cursor:K?"pointer":"",ishot:!0,"text-anchor":"end"}).css(A.style),i.appendChild(Q));Ea(A.endDate)&&A.endDate!==""&&(z=v.text().attr({text:A.endDate,x:P+E+2+L,y:n+C*0.5,cursor:K?"pointer":"",ishot:!0,"text-anchor":"start"}).css(A.style),i.appendChild(z));q.graphic=H;q.percentCompleteGraphic=r;q.slackGraphic=O;q.dataLabel=N;q.startLabel=Q;q.endLabel=z;r&&r.click(G).data("link",K).data("dataObj",A);O&&O.click(G).data("link",K).data("dataObj",A);A.showHoverEffect&&ra([H,N,Q,z],function(a){a&&
a.click(G).hover(function(){b.taskHoverHandler.call(this,b)},function(){b.taskHoverOutHandler.call(this,b)}).data("link",K).data("dataObj",A)})}this.drawConnectors();u=null;f=k&&k.length;for(M=0;M<f;M+=1)if(d=k[M],n=l[d.taskId],u=d.items||(d.items={}),n)x=ga.animation({"fill-opacity":d.fillAlpha,"stroke-opacity":d.borderAlpha},y,"normal"),u.graphic=v.polypath(d.numSides,o.getPixel(d.date.ms),n.y+n.h*0.5,c(d.radius,n.h*0.6),d.startAngle,d.depth,a).attr({fill:d.fillColor,"fill-opacity":0,stroke:d.borderColor,
"stroke-opacity":0,ishot:!0,cursor:d.link?"pointer":"","stroke-width":d.borderThickness}).animate(x.delay(y)).tooltip(d.toolText).click(function(){var a=this.data("link");a&&b.linkClickFN.call({link:a},b)}).data("link",d.link).data("dataObj",d),d.showHoverEffect&&u.graphic.hover(function(){var a=this.data("dataObj");a.items.graphic.attr({fill:a.hoverFillColor,stroke:a.hoverBorderColor,"fill-opacity":a.hoverFillAlpha,"stroke-opacity":a.hoverBorderAlpha})},function(){var a=this.data("dataObj");a.items.graphic.attr({fill:a.fillColor,
stroke:a.borderColor,"fill-opacity":a.fillAlpha,"stroke-opacity":a.borderAlpha})})},taskHoverOutHandler:function(a){var b=a.options.tasksMap,a=this.data("dataObj"),b=b[e(a.id,a.index)].items,c={fill:a.color,stroke:a.borderColor,"stroke-width":a.borderThickness,"stroke-dasharray":a.dashedStyle};a.percentComplete!==-1&&!a.showAsGroup&&(b.slackGraphic.attr({fill:a.slackColor}),b.percentCompleteGraphic.attr({fill:a.color}),delete c.fill);b.graphic.attr(c)},taskHoverHandler:function(a){var b=a.options.tasksMap,
a=this.data("dataObj"),b=b[e(a.id,a.index)].items,c={fill:a.hoverFillColor,stroke:a.hoverBorderColor};a.percentComplete!==-1&&!a.showAsGroup&&(b.slackGraphic.attr({fill:a.slackHoverColor}),b.percentCompleteGraphic.attr({fill:a.hoverFillColor}),delete c.fill);b.graphic.attr(c)},drawConnectors:function(){var a=this,b=a.paper,c=a.options,d=c.chart.connectorExtension,e=c.connectors,h=c.tasksMap,x=e.length,m=a.layers.dataset,f=[],c=c.plotOptions.series,c=isNaN(+c.animation)&&c.animation.duration||c.animation*
1E3,i,B,p,t,o,j,g,y,l,k,q,r;for(i=0;i<=x;i+=1)if(p=e[i]||{},j=p.fromTaskId,t=p.toTaskId,B=h[j],l=h[t],t=p.items||(p.items={}),B&&l){k=B.y+B.h*0.5;q=l.y+l.h*0.5;o=k==q;j=B.x;g=B.x+B.w;y=l.x;l=l.x+l.w;r=r=0;p.fromTaskConnectStart==0&&p.toTaskConnectStart==1&&(r=1);p.fromTaskConnectStart==0&&p.toTaskConnectStart==0&&(r=2);p.fromTaskConnectStart==1&&p.toTaskConnectStart==1&&(r=3);p.fromTaskConnectStart==1&&p.toTaskConnectStart==0&&(r=4);if(o)switch(B=B.height,r){case 1:r=(y-g)/10;f=["M",g,k,g+r,k,"L",
g+r,k,g+r,k-B,"L",g+r,k-B,y-r,k-B,"L",y-r,k-B,y-r,k,"L",y-r,k,y,q,"L",l+d,q,l,q];break;case 2:f=["M",g,k,g+d,k,"L",g+d,k,g+d,k-B,"L",g+d,k-B,l+d,k-B,"L",l+d,q-B,l+d,q];break;case 3:f=["M",j,k,j-d,k,"L",j-d,k,j-d,k-B,"L",j-d,k-B,y-d,k-B,"L",y-d,k-B,y-d,k,"L",y-d,k,y,k];break;case 4:f=["M",j,k,j-d,k,"L",j-d,k,j-d,k-B,"L",j-d,k-B,l+d,k-B,"L",l+d,k-B,l+d,k,"L",l+d,k,l,k]}else switch(r){case 1:f=["M",g,k,g+(y-g)/2,k,"L",g+(y-g)/2,k,g+(y-g)/2,q,"L",g+(y-g)/2,q,y,q];f=g<=y?["M",g,k,g+(y-g)/2,k,"L",g+(y-
g)/2,k,g+(y-g)/2,q,"L",g+(y-g)/2,q,y,q]:["M",g,k,g+d,k,"L",g+d,k,g+d,k+(q-k)/2,"L",g+d,k+(q-k)/2,y-d,k+(q-k)/2,"L",y-d,k+(q-k)/2,y-d,q,"L",y-d,q,y,q];break;case 2:r=l-g<0?0:l-g;f=["M",g,k,g+d+r,k,"L",g+d+r,k,g+d+r,q,"L",g+d+r,q,l,q];break;case 3:r=j-y<0?0:j-y;f=["M",j,k,j-d-r,k,"L",j-d-r,k,j-d-r,q,"L",j-d-r,q,y,q];break;case 4:f=j>l?["M",j,k,j-(j-l)/2,k,"L",j-(j-l)/2,k,j-(j-l)/2,q,"L",j-(j-l)/2,q,l,q]:["M",j,k,j-d,k,"L",j-d,k,j-d,k+(q-k)/2,"L",j-d,k+(q-k)/2,l+d,k+(q-k)/2,"L",l+d,k+(q-k)/2,l+d,q,"L",
l+d,q,l,q]}t.connector?t.connector.animate({path:f}):(j=ga.animation({"stroke-opacity":p.alpha},c,"normal"),t.connector=b.path(f,m).attr({stroke:p.color,"stroke-opacity":0,"stroke-width":p.thickness,"stroke-dasharray":p.dashedStyle}).animate(j.delay(c)));t.tracker=b.path(f,m).attr({stroke:na,"stroke-width":U(p.thickness,10),ishot:!0,cursor:p.link?"pointer":""}).data("dataObj",p).data("link",p.link).click(function(){var b=this.data("link"),c=this.data("dataObj");b&&a.linkClickFN.call({link:b},a);b=
{fromTaskId:c.fromTaskId,toTaskId:c.toTaskId,fromTaskConnectStart:c.fromTaskConnectStart,toTaskConnectStart:c.toTaskConnectStart};I.raiseEvent("connectorclicked",b,a.logic.chartInstance,[a.logic.chartInstance.id,b.fromTaskId,b.toTaskId,b.fromTaskConnectStart,b.toTaskConnectStart])});p.showHoverEffect&&t.tracker.hover(function(){var a=this.data("dataObj"),b={stroke:a.hoverColor,"stroke-dasharray":a.dashedStyle,"stroke-width":a.hoverThickness};ra([h[a.fromTaskId],h[a.toTaskId]],function(a){var b={fill:a.dataObj.hoverFillColor,
stroke:a.dataObj.hoverBorderColor};a.dataObj.percentComplete!==-1&&!a.dataObj.showAsGroup&&(a.items.slackGraphic.attr({fill:a.dataObj.slackHoverColor}),a.items.percentCompleteGraphic.attr({fill:a.dataObj.hoverFillColor,stroke:a.dataObj.hoverBorderColor}),delete b.fill);a.items.graphic.attr(b)});a.items.connector.attr(b)},function(){var a=this.data("dataObj"),b={stroke:a.color,"stroke-width":a.thickness,"stroke-dasharray":a.dashedStyle};ra([h[a.fromTaskId],h[a.toTaskId]],function(a){var b={fill:a.dataObj.color,
stroke:a.dataObj.borderColor,"stroke-width":a.dataObj.borderThickness,"stroke-dasharray":a.dataObj.dashedStyle};a.dataObj.percentComplete!==-1&&!a.dataObj.showAsGroup&&(a.items.slackGraphic.attr({fill:a.dataObj.slackColor}),a.items.percentCompleteGraphic.attr({fill:a.dataObj.color}),delete b.fill);a.items.graphic.attr(b)});a.items.connector.attr(b)})}}},Ba["renderer.cartesian"])}]);