package com.redmoon.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DocServiceService service = new DocServiceService();
 * DocService portType = service.getDocServicePort();
 * portType.create(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DocServiceService", targetNamespace = "http://webservice.redmoon.com/", wsdlLocation = "http://www.cwbbs.com:8080/DocService?wsdl")
public class DocServiceService extends Service {

	private final static URL DOCSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.redmoon.webservice.DocServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.redmoon.webservice.DocServiceService.class
					.getResource(".");
			url = new URL(baseUrl, "http://www.cwbbs.com:8080/DocService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://www.cwbbs.com:8080/DocService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DOCSERVICESERVICE_WSDL_LOCATION = url;
	}

	public DocServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DocServiceService() {
		super(DOCSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://webservice.redmoon.com/", "DocServiceService"));
	}

	/**
	 * 
	 * @return returns DocService
	 */
	@WebEndpoint(name = "DocServicePort")
	public DocService getDocServicePort() {
		return super.getPort(new QName("http://webservice.redmoon.com/",
				"DocServicePort"), DocService.class);
	}

}
