package com.redmoon.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DocService", targetNamespace = "http://webservice.redmoon.com/")
public interface DocService {

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 * @param arg7
	 * @param arg8
	 * @param arg9
	 * @return returns long
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "create", targetNamespace = "http://webservice.redmoon.com/", className = "com.redmoon.webservice.Create")
	@ResponseWrapper(localName = "createResponse", targetNamespace = "http://webservice.redmoon.com/", className = "com.redmoon.webservice.CreateResponse")
	public long create(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4,
			@WebParam(name = "arg5", targetNamespace = "") int arg5,
			@WebParam(name = "arg6", targetNamespace = "") String arg6,
			@WebParam(name = "arg7", targetNamespace = "") String arg7,
			@WebParam(name = "arg8", targetNamespace = "") String arg8,
			@WebParam(name = "arg9", targetNamespace = "") int arg9);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDirectoryOptions", targetNamespace = "http://webservice.redmoon.com/", className = "com.redmoon.webservice.GetDirectoryOptions")
	@ResponseWrapper(localName = "getDirectoryOptionsResponse", targetNamespace = "http://webservice.redmoon.com/", className = "com.redmoon.webservice.GetDirectoryOptionsResponse")
	public String getDirectoryOptions(
			@WebParam(name = "arg0", targetNamespace = "") boolean arg0);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "createFile", targetNamespace = "http://webservice.redmoon.com/", className = "com.redmoon.webservice.CreateFile")
	@ResponseWrapper(localName = "createFileResponse", targetNamespace = "http://webservice.redmoon.com/", className = "com.redmoon.webservice.CreateFileResponse")
	public boolean createFile(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") long arg1,
			@WebParam(name = "arg2", targetNamespace = "") byte[] arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

}
